// Code generated by fhir-gen; DO NOT EDIT.

package r4

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// Address is the generated FHIR Address datatype.
type Address struct {
	Element
	Use               *AddressUse              `json:"use,omitempty"`
	UseElement        *fhir.PrimitiveElement   `json:"-"`
	Type              *AddressType             `json:"type,omitempty"`
	TypeElement       *fhir.PrimitiveElement   `json:"-"`
	Text              *string                  `json:"text,omitempty"`
	TextElement       *fhir.PrimitiveElement   `json:"-"`
	Line              []string                 `json:"line,omitempty"`
	LineElement       []*fhir.PrimitiveElement `json:"-"`
	City              *string                  `json:"city,omitempty"`
	CityElement       *fhir.PrimitiveElement   `json:"-"`
	District          *string                  `json:"district,omitempty"`
	DistrictElement   *fhir.PrimitiveElement   `json:"-"`
	State             *string                  `json:"state,omitempty"`
	StateElement      *fhir.PrimitiveElement   `json:"-"`
	PostalCode        *string                  `json:"postalCode,omitempty"`
	PostalCodeElement *fhir.PrimitiveElement   `json:"-"`
	Country           *string                  `json:"country,omitempty"`
	CountryElement    *fhir.PrimitiveElement   `json:"-"`
	Period            *Period                  `json:"period,omitempty"`
}

// MarshalJSON folds the primitive "_field" siblings into the encoded value: a scalar
// sibling is dropped when it carries no id or extension, and a repeating sibling's
// array is null-aligned with its value array, so a partially-extended repeating
// primitive lines up position-for-position on the wire (a position with no
// id/extension becomes a JSON null in the "_field" array).
func (v Address) MarshalJSON() ([]byte, error) {
	type alias Address
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalAddressSiblings(&v, encoded)
}

// marshalAddressSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalAddressSiblings(v *Address, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.UseElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_use", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TypeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_type", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TextElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_text", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CityElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_city", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DistrictElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_district", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_state", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PostalCodeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_postalCode", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CountryElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_country", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.Line), v.LineElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_line", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *Address) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_use"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.UseElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_type"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TypeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_text"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TextElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_city"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CityElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_district"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DistrictElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_state"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_postalCode"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PostalCodeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_country"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CountryElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_line"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.LineElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias Address
	return json.Unmarshal(residual, (*alias)(v))
}
