// Code generated by fhir-gen; DO NOT EDIT.

package r4

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// CarePlanResourceType is the FHIR resourceType discriminator for CarePlan.
const CarePlanResourceType = "CarePlan"

// CarePlan is the generated FHIR CarePlan resource.
type CarePlan struct {
	DomainResource
	Identifier                   []Identifier             `json:"identifier,omitempty"`
	InstantiatesCanonical        []string                 `json:"instantiatesCanonical,omitempty"`
	InstantiatesCanonicalElement []*fhir.PrimitiveElement `json:"-"`
	InstantiatesUri              []string                 `json:"instantiatesUri,omitempty"`
	InstantiatesUriElement       []*fhir.PrimitiveElement `json:"-"`
	BasedOn                      []Reference              `json:"basedOn,omitempty"`
	Replaces                     []Reference              `json:"replaces,omitempty"`
	PartOf                       []Reference              `json:"partOf,omitempty"`
	Status                       *RequestStatus           `json:"status,omitempty"`
	StatusElement                *fhir.PrimitiveElement   `json:"-"`
	Intent                       *CarePlanIntent          `json:"intent,omitempty"`
	IntentElement                *fhir.PrimitiveElement   `json:"-"`
	Category                     []CodeableConcept        `json:"category,omitempty"`
	Title                        *string                  `json:"title,omitempty"`
	TitleElement                 *fhir.PrimitiveElement   `json:"-"`
	Description                  *string                  `json:"description,omitempty"`
	DescriptionElement           *fhir.PrimitiveElement   `json:"-"`
	Subject                      *Reference               `json:"subject,omitempty"`
	Encounter                    *Reference               `json:"encounter,omitempty"`
	Period                       *Period                  `json:"period,omitempty"`
	Created                      *string                  `json:"created,omitempty"`
	CreatedElement               *fhir.PrimitiveElement   `json:"-"`
	Author                       *Reference               `json:"author,omitempty"`
	Contributor                  []Reference              `json:"contributor,omitempty"`
	CareTeam                     []Reference              `json:"careTeam,omitempty"`
	Addresses                    []Reference              `json:"addresses,omitempty"`
	SupportingInfo               []Reference              `json:"supportingInfo,omitempty"`
	Goal                         []Reference              `json:"goal,omitempty"`
	Activity                     []CarePlanActivity       `json:"activity,omitempty"`
	Note                         []Annotation             `json:"note,omitempty"`
}

// ResourceType returns the FHIR discriminator "CarePlan".
func (r *CarePlan) ResourceType() string { return CarePlanResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a CarePlan never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *CarePlan) MarshalJSON() ([]byte, error) {
	type alias CarePlan
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: CarePlanResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalCarePlanSiblings(r, encoded)
}

// marshalCarePlanSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCarePlanSiblings(v *CarePlan, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.IntentElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_intent", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_title", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CreatedElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_created", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.InstantiatesCanonical), v.InstantiatesCanonicalElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_instantiatesCanonical", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.InstantiatesUri), v.InstantiatesUriElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_instantiatesUri", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through fhir.UnmarshalResource so the concrete type behind the interface is recovered;
// the standard codec cannot decode a resource object into an interface.
func (v *CarePlan) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_intent"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.IntentElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_title"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_created"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CreatedElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_instantiatesCanonical"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.InstantiatesCanonicalElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_instantiatesUri"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.InstantiatesUriElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := fhir.UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CarePlan
	return json.Unmarshal(residual, (*alias)(v))
}

// CarePlanActivity is a generated nested backbone element.
type CarePlanActivity struct {
	BackboneElement
	OutcomeCodeableConcept []CodeableConcept       `json:"outcomeCodeableConcept,omitempty"`
	OutcomeReference       []Reference             `json:"outcomeReference,omitempty"`
	Progress               []Annotation            `json:"progress,omitempty"`
	Reference              *Reference              `json:"reference,omitempty"`
	Detail                 *CarePlanActivityDetail `json:"detail,omitempty"`
}

// CarePlanActivityDetail is a generated nested backbone element.
type CarePlanActivityDetail struct {
	BackboneElement
	Kind                         *CarePlanActivityKind    `json:"kind,omitempty"`
	KindElement                  *fhir.PrimitiveElement   `json:"-"`
	InstantiatesCanonical        []string                 `json:"instantiatesCanonical,omitempty"`
	InstantiatesCanonicalElement []*fhir.PrimitiveElement `json:"-"`
	InstantiatesUri              []string                 `json:"instantiatesUri,omitempty"`
	InstantiatesUriElement       []*fhir.PrimitiveElement `json:"-"`
	Code                         *CodeableConcept         `json:"code,omitempty"`
	ReasonCode                   []CodeableConcept        `json:"reasonCode,omitempty"`
	ReasonReference              []Reference              `json:"reasonReference,omitempty"`
	Goal                         []Reference              `json:"goal,omitempty"`
	Status                       *CarePlanActivityStatus  `json:"status,omitempty"`
	StatusElement                *fhir.PrimitiveElement   `json:"-"`
	StatusReason                 *CodeableConcept         `json:"statusReason,omitempty"`
	DoNotPerform                 *bool                    `json:"doNotPerform,omitempty"`
	DoNotPerformElement          *fhir.PrimitiveElement   `json:"-"`
	ScheduledTiming              *Timing                  `json:"scheduledTiming,omitempty"`
	ScheduledPeriod              *Period                  `json:"scheduledPeriod,omitempty"`
	ScheduledString              *FHIRString              `json:"scheduledString,omitempty"`
	Location                     *Reference               `json:"location,omitempty"`
	Performer                    []Reference              `json:"performer,omitempty"`
	ProductCodeableConcept       *CodeableConcept         `json:"productCodeableConcept,omitempty"`
	ProductReference             *Reference               `json:"productReference,omitempty"`
	DailyAmount                  *Quantity                `json:"dailyAmount,omitempty"`
	Quantity                     *Quantity                `json:"quantity,omitempty"`
	Description                  *string                  `json:"description,omitempty"`
	DescriptionElement           *fhir.PrimitiveElement   `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CarePlanActivityDetail) MarshalJSON() ([]byte, error) {
	type alias CarePlanActivityDetail
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCarePlanActivityDetailSiblings(&v, encoded)
}

// marshalCarePlanActivityDetailSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCarePlanActivityDetailSiblings(v *CarePlanActivityDetail, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.KindElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_kind", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DoNotPerformElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_doNotPerform", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.InstantiatesCanonical), v.InstantiatesCanonicalElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_instantiatesCanonical", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.InstantiatesUri), v.InstantiatesUriElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_instantiatesUri", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CarePlanActivityDetail) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_kind"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.KindElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_doNotPerform"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DoNotPerformElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_instantiatesCanonical"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.InstantiatesCanonicalElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_instantiatesUri"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.InstantiatesUriElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CarePlanActivityDetail
	return json.Unmarshal(residual, (*alias)(v))
}

// CarePlanActivityDetailScheduled is the sealed value interface for the scheduled[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isCarePlanActivityDetailScheduled marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type CarePlanActivityDetailScheduled interface{ isCarePlanActivityDetailScheduled() }

func (Timing) isCarePlanActivityDetailScheduled()     {}
func (Period) isCarePlanActivityDetailScheduled()     {}
func (FHIRString) isCarePlanActivityDetailScheduled() {}

// Scheduled returns the value set in the scheduled[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *CarePlanActivityDetail) Scheduled() (CarePlanActivityDetailScheduled, bool) {
	switch {
	case r.ScheduledTiming != nil:
		return *r.ScheduledTiming, true
	case r.ScheduledPeriod != nil:
		return *r.ScheduledPeriod, true
	case r.ScheduledString != nil:
		return *r.ScheduledString, true
	}
	return nil, false
}

// SetScheduledTiming sets scheduled[x] to a Timing and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *CarePlanActivityDetail) SetScheduledTiming(v Timing) {
	r.ScheduledTiming = nil
	r.ScheduledPeriod = nil
	r.ScheduledString = nil
	r.ScheduledTiming = &v
}

// SetScheduledPeriod sets scheduled[x] to a Period and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *CarePlanActivityDetail) SetScheduledPeriod(v Period) {
	r.ScheduledTiming = nil
	r.ScheduledPeriod = nil
	r.ScheduledString = nil
	r.ScheduledPeriod = &v
}

// SetScheduledString sets scheduled[x] to a FHIRString (the
// release primitive wrapper that carries the isCarePlanActivityDetailScheduled marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *CarePlanActivityDetail) SetScheduledString(v FHIRString) {
	r.ScheduledTiming = nil
	r.ScheduledPeriod = nil
	r.ScheduledString = nil
	r.ScheduledString = &v
}

// CarePlanActivityDetailProduct is the sealed value interface for the product[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isCarePlanActivityDetailProduct marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type CarePlanActivityDetailProduct interface{ isCarePlanActivityDetailProduct() }

func (CodeableConcept) isCarePlanActivityDetailProduct() {}
func (Reference) isCarePlanActivityDetailProduct()       {}

// Product returns the value set in the product[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *CarePlanActivityDetail) Product() (CarePlanActivityDetailProduct, bool) {
	switch {
	case r.ProductCodeableConcept != nil:
		return *r.ProductCodeableConcept, true
	case r.ProductReference != nil:
		return *r.ProductReference, true
	}
	return nil, false
}

// SetProductCodeableConcept sets product[x] to a CodeableConcept and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *CarePlanActivityDetail) SetProductCodeableConcept(v CodeableConcept) {
	r.ProductCodeableConcept = nil
	r.ProductReference = nil
	r.ProductCodeableConcept = &v
}

// SetProductReference sets product[x] to a Reference and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *CarePlanActivityDetail) SetProductReference(v Reference) {
	r.ProductCodeableConcept = nil
	r.ProductReference = nil
	r.ProductReference = &v
}
