// Code generated by fhir-gen; DO NOT EDIT.

package r4

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// DeviceMetricResourceType is the FHIR resourceType discriminator for DeviceMetric.
const DeviceMetricResourceType = "DeviceMetric"

// DeviceMetric is the generated FHIR DeviceMetric resource.
type DeviceMetric struct {
	DomainResource
	Identifier               []Identifier                   `json:"identifier,omitempty"`
	Type                     *CodeableConcept               `json:"type,omitempty"`
	Unit                     *CodeableConcept               `json:"unit,omitempty"`
	Source                   *Reference                     `json:"source,omitempty"`
	Parent                   *Reference                     `json:"parent,omitempty"`
	OperationalStatus        *DeviceMetricOperationalStatus `json:"operationalStatus,omitempty"`
	OperationalStatusElement *fhir.PrimitiveElement         `json:"-"`
	Color                    *DeviceMetricColor             `json:"color,omitempty"`
	ColorElement             *fhir.PrimitiveElement         `json:"-"`
	Category                 *DeviceMetricCategory          `json:"category,omitempty"`
	CategoryElement          *fhir.PrimitiveElement         `json:"-"`
	MeasurementPeriod        *Timing                        `json:"measurementPeriod,omitempty"`
	Calibration              []DeviceMetricCalibration      `json:"calibration,omitempty"`
}

// ResourceType returns the FHIR discriminator "DeviceMetric".
func (r *DeviceMetric) ResourceType() string { return DeviceMetricResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a DeviceMetric never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *DeviceMetric) MarshalJSON() ([]byte, error) {
	type alias DeviceMetric
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: DeviceMetricResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalDeviceMetricSiblings(r, encoded)
}

// marshalDeviceMetricSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalDeviceMetricSiblings(v *DeviceMetric, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.OperationalStatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_operationalStatus", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ColorElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_color", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CategoryElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_category", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through fhir.UnmarshalResource so the concrete type behind the interface is recovered;
// the standard codec cannot decode a resource object into an interface.
func (v *DeviceMetric) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_operationalStatus"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.OperationalStatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_color"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ColorElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_category"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CategoryElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := fhir.UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias DeviceMetric
	return json.Unmarshal(residual, (*alias)(v))
}

// DeviceMetricCalibration is a generated nested backbone element.
type DeviceMetricCalibration struct {
	BackboneElement
	Type         *DeviceMetricCalibrationType  `json:"type,omitempty"`
	TypeElement  *fhir.PrimitiveElement        `json:"-"`
	State        *DeviceMetricCalibrationState `json:"state,omitempty"`
	StateElement *fhir.PrimitiveElement        `json:"-"`
	Time         *string                       `json:"time,omitempty"`
	TimeElement  *fhir.PrimitiveElement        `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v DeviceMetricCalibration) MarshalJSON() ([]byte, error) {
	type alias DeviceMetricCalibration
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalDeviceMetricCalibrationSiblings(&v, encoded)
}

// marshalDeviceMetricCalibrationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalDeviceMetricCalibrationSiblings(v *DeviceMetricCalibration, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TypeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_type", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_state", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TimeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_time", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *DeviceMetricCalibration) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_type"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TypeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_state"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_time"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TimeElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias DeviceMetricCalibration
	return json.Unmarshal(residual, (*alias)(v))
}
