// Code generated by fhir-gen; DO NOT EDIT.

package r4

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// EvidenceResourceType is the FHIR resourceType discriminator for Evidence.
const EvidenceResourceType = "Evidence"

// Evidence is the generated FHIR Evidence resource.
type Evidence struct {
	DomainResource
	URL                   *string                `json:"url,omitempty"`
	URLElement            *fhir.PrimitiveElement `json:"-"`
	Identifier            []Identifier           `json:"identifier,omitempty"`
	Version               *string                `json:"version,omitempty"`
	VersionElement        *fhir.PrimitiveElement `json:"-"`
	Name                  *string                `json:"name,omitempty"`
	NameElement           *fhir.PrimitiveElement `json:"-"`
	Title                 *string                `json:"title,omitempty"`
	TitleElement          *fhir.PrimitiveElement `json:"-"`
	ShortTitle            *string                `json:"shortTitle,omitempty"`
	ShortTitleElement     *fhir.PrimitiveElement `json:"-"`
	Subtitle              *string                `json:"subtitle,omitempty"`
	SubtitleElement       *fhir.PrimitiveElement `json:"-"`
	Status                *PublicationStatus     `json:"status,omitempty"`
	StatusElement         *fhir.PrimitiveElement `json:"-"`
	Date                  *string                `json:"date,omitempty"`
	DateElement           *fhir.PrimitiveElement `json:"-"`
	Publisher             *string                `json:"publisher,omitempty"`
	PublisherElement      *fhir.PrimitiveElement `json:"-"`
	Contact               []ContactDetail        `json:"contact,omitempty"`
	Description           *string                `json:"description,omitempty"`
	DescriptionElement    *fhir.PrimitiveElement `json:"-"`
	Note                  []Annotation           `json:"note,omitempty"`
	UseContext            []UsageContext         `json:"useContext,omitempty"`
	Jurisdiction          []CodeableConcept      `json:"jurisdiction,omitempty"`
	Copyright             *string                `json:"copyright,omitempty"`
	CopyrightElement      *fhir.PrimitiveElement `json:"-"`
	ApprovalDate          *string                `json:"approvalDate,omitempty"`
	ApprovalDateElement   *fhir.PrimitiveElement `json:"-"`
	LastReviewDate        *string                `json:"lastReviewDate,omitempty"`
	LastReviewDateElement *fhir.PrimitiveElement `json:"-"`
	EffectivePeriod       *Period                `json:"effectivePeriod,omitempty"`
	Topic                 []CodeableConcept      `json:"topic,omitempty"`
	Author                []ContactDetail        `json:"author,omitempty"`
	Editor                []ContactDetail        `json:"editor,omitempty"`
	Reviewer              []ContactDetail        `json:"reviewer,omitempty"`
	Endorser              []ContactDetail        `json:"endorser,omitempty"`
	RelatedArtifact       []RelatedArtifact      `json:"relatedArtifact,omitempty"`
	ExposureBackground    *Reference             `json:"exposureBackground,omitempty"`
	ExposureVariant       []Reference            `json:"exposureVariant,omitempty"`
	Outcome               []Reference            `json:"outcome,omitempty"`
}

// ResourceType returns the FHIR discriminator "Evidence".
func (r *Evidence) ResourceType() string { return EvidenceResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a Evidence never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *Evidence) MarshalJSON() ([]byte, error) {
	type alias Evidence
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: EvidenceResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalEvidenceSiblings(r, encoded)
}

// marshalEvidenceSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalEvidenceSiblings(v *Evidence, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.URLElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_url", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_title", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ShortTitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_shortTitle", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.SubtitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_subtitle", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublisherElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publisher", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyright", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ApprovalDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_approvalDate", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.LastReviewDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_lastReviewDate", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through the release-local UnmarshalResource so the concrete type behind the interface
// is recovered as a resource of this release; the standard codec cannot decode a resource
// object into an interface.
func (v *Evidence) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_url"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URLElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_title"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_shortTitle"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ShortTitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_subtitle"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.SubtitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_publisher"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublisherElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyright"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_approvalDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ApprovalDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_lastReviewDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.LastReviewDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias Evidence
	return json.Unmarshal(residual, (*alias)(v))
}
