// Code generated by fhir-gen; DO NOT EDIT.

package r4

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// GraphDefinitionResourceType is the FHIR resourceType discriminator for GraphDefinition.
const GraphDefinitionResourceType = "GraphDefinition"

// GraphDefinition is the generated FHIR GraphDefinition resource.
type GraphDefinition struct {
	DomainResource
	URL                 *string                `json:"url,omitempty"`
	URLElement          *fhir.PrimitiveElement `json:"-"`
	Version             *string                `json:"version,omitempty"`
	VersionElement      *fhir.PrimitiveElement `json:"-"`
	Name                *string                `json:"name,omitempty"`
	NameElement         *fhir.PrimitiveElement `json:"-"`
	Status              *PublicationStatus     `json:"status,omitempty"`
	StatusElement       *fhir.PrimitiveElement `json:"-"`
	Experimental        *bool                  `json:"experimental,omitempty"`
	ExperimentalElement *fhir.PrimitiveElement `json:"-"`
	Date                *string                `json:"date,omitempty"`
	DateElement         *fhir.PrimitiveElement `json:"-"`
	Publisher           *string                `json:"publisher,omitempty"`
	PublisherElement    *fhir.PrimitiveElement `json:"-"`
	Contact             []ContactDetail        `json:"contact,omitempty"`
	Description         *string                `json:"description,omitempty"`
	DescriptionElement  *fhir.PrimitiveElement `json:"-"`
	UseContext          []UsageContext         `json:"useContext,omitempty"`
	Jurisdiction        []CodeableConcept      `json:"jurisdiction,omitempty"`
	Purpose             *string                `json:"purpose,omitempty"`
	PurposeElement      *fhir.PrimitiveElement `json:"-"`
	Start               *ResourceType          `json:"start,omitempty"`
	StartElement        *fhir.PrimitiveElement `json:"-"`
	Profile             *string                `json:"profile,omitempty"`
	ProfileElement      *fhir.PrimitiveElement `json:"-"`
	Link                []GraphDefinitionLink  `json:"link,omitempty"`
}

// ResourceType returns the FHIR discriminator "GraphDefinition".
func (r *GraphDefinition) ResourceType() string { return GraphDefinitionResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a GraphDefinition never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *GraphDefinition) MarshalJSON() ([]byte, error) {
	type alias GraphDefinition
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: GraphDefinitionResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalGraphDefinitionSiblings(r, encoded)
}

// marshalGraphDefinitionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalGraphDefinitionSiblings(v *GraphDefinition, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.URLElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_url", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ExperimentalElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_experimental", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublisherElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publisher", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PurposeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_purpose", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StartElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_start", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ProfileElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_profile", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through the release-local UnmarshalResource so the concrete type behind the interface
// is recovered as a resource of this release; the standard codec cannot decode a resource
// object into an interface.
func (v *GraphDefinition) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_url"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URLElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_experimental"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ExperimentalElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_publisher"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublisherElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_purpose"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PurposeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_start"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StartElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_profile"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ProfileElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias GraphDefinition
	return json.Unmarshal(residual, (*alias)(v))
}

// GraphDefinitionLink is a generated nested backbone element.
type GraphDefinitionLink struct {
	BackboneElement
	Path               *string                     `json:"path,omitempty"`
	PathElement        *fhir.PrimitiveElement      `json:"-"`
	SliceName          *string                     `json:"sliceName,omitempty"`
	SliceNameElement   *fhir.PrimitiveElement      `json:"-"`
	Min                *int32                      `json:"min,omitempty"`
	MinElement         *fhir.PrimitiveElement      `json:"-"`
	Max                *string                     `json:"max,omitempty"`
	MaxElement         *fhir.PrimitiveElement      `json:"-"`
	Description        *string                     `json:"description,omitempty"`
	DescriptionElement *fhir.PrimitiveElement      `json:"-"`
	Target             []GraphDefinitionLinkTarget `json:"target,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v GraphDefinitionLink) MarshalJSON() ([]byte, error) {
	type alias GraphDefinitionLink
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalGraphDefinitionLinkSiblings(&v, encoded)
}

// marshalGraphDefinitionLinkSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalGraphDefinitionLinkSiblings(v *GraphDefinitionLink, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.PathElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_path", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.SliceNameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_sliceName", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.MinElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_min", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.MaxElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_max", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *GraphDefinitionLink) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_path"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PathElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_sliceName"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.SliceNameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_min"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.MinElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_max"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.MaxElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias GraphDefinitionLink
	return json.Unmarshal(residual, (*alias)(v))
}

// GraphDefinitionLinkTarget is a generated nested backbone element.
type GraphDefinitionLinkTarget struct {
	BackboneElement
	Type           *ResourceType                          `json:"type,omitempty"`
	TypeElement    *fhir.PrimitiveElement                 `json:"-"`
	Params         *string                                `json:"params,omitempty"`
	ParamsElement  *fhir.PrimitiveElement                 `json:"-"`
	Profile        *string                                `json:"profile,omitempty"`
	ProfileElement *fhir.PrimitiveElement                 `json:"-"`
	Compartment    []GraphDefinitionLinkTargetCompartment `json:"compartment,omitempty"`
	Link           []GraphDefinitionLink                  `json:"link,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v GraphDefinitionLinkTarget) MarshalJSON() ([]byte, error) {
	type alias GraphDefinitionLinkTarget
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalGraphDefinitionLinkTargetSiblings(&v, encoded)
}

// marshalGraphDefinitionLinkTargetSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalGraphDefinitionLinkTargetSiblings(v *GraphDefinitionLinkTarget, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TypeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_type", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ParamsElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_params", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ProfileElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_profile", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *GraphDefinitionLinkTarget) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_type"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TypeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_params"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ParamsElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_profile"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ProfileElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias GraphDefinitionLinkTarget
	return json.Unmarshal(residual, (*alias)(v))
}

// GraphDefinitionLinkTargetCompartment is a generated nested backbone element.
type GraphDefinitionLinkTargetCompartment struct {
	BackboneElement
	Use                *GraphCompartmentUse   `json:"use,omitempty"`
	UseElement         *fhir.PrimitiveElement `json:"-"`
	Code               *CompartmentType       `json:"code,omitempty"`
	CodeElement        *fhir.PrimitiveElement `json:"-"`
	Rule               *GraphCompartmentRule  `json:"rule,omitempty"`
	RuleElement        *fhir.PrimitiveElement `json:"-"`
	Expression         *string                `json:"expression,omitempty"`
	ExpressionElement  *fhir.PrimitiveElement `json:"-"`
	Description        *string                `json:"description,omitempty"`
	DescriptionElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v GraphDefinitionLinkTargetCompartment) MarshalJSON() ([]byte, error) {
	type alias GraphDefinitionLinkTargetCompartment
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalGraphDefinitionLinkTargetCompartmentSiblings(&v, encoded)
}

// marshalGraphDefinitionLinkTargetCompartmentSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalGraphDefinitionLinkTargetCompartmentSiblings(v *GraphDefinitionLinkTargetCompartment, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.UseElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_use", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CodeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_code", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.RuleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_rule", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ExpressionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_expression", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *GraphDefinitionLinkTargetCompartment) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_use"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.UseElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_code"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CodeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_rule"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.RuleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_expression"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ExpressionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias GraphDefinitionLinkTargetCompartment
	return json.Unmarshal(residual, (*alias)(v))
}
