// Code generated by fhir-gen; DO NOT EDIT.

package r4

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// MeasureReportResourceType is the FHIR resourceType discriminator for MeasureReport.
const MeasureReportResourceType = "MeasureReport"

// MeasureReport is the generated FHIR MeasureReport resource.
type MeasureReport struct {
	DomainResource
	Identifier          []Identifier           `json:"identifier,omitempty"`
	Status              *MeasureReportStatus   `json:"status,omitempty"`
	StatusElement       *fhir.PrimitiveElement `json:"-"`
	Type                *MeasureReportType     `json:"type,omitempty"`
	TypeElement         *fhir.PrimitiveElement `json:"-"`
	Measure             *string                `json:"measure,omitempty"`
	MeasureElement      *fhir.PrimitiveElement `json:"-"`
	Subject             *Reference             `json:"subject,omitempty"`
	Date                *string                `json:"date,omitempty"`
	DateElement         *fhir.PrimitiveElement `json:"-"`
	Reporter            *Reference             `json:"reporter,omitempty"`
	Period              *Period                `json:"period,omitempty"`
	ImprovementNotation *CodeableConcept       `json:"improvementNotation,omitempty"`
	Group               []MeasureReportGroup   `json:"group,omitempty"`
	EvaluatedResource   []Reference            `json:"evaluatedResource,omitempty"`
}

// ResourceType returns the FHIR discriminator "MeasureReport".
func (r *MeasureReport) ResourceType() string { return MeasureReportResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a MeasureReport never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *MeasureReport) MarshalJSON() ([]byte, error) {
	type alias MeasureReport
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: MeasureReportResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalMeasureReportSiblings(r, encoded)
}

// marshalMeasureReportSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalMeasureReportSiblings(v *MeasureReport, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TypeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_type", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.MeasureElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_measure", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through the release-local UnmarshalResource so the concrete type behind the interface
// is recovered as a resource of this release; the standard codec cannot decode a resource
// object into an interface.
func (v *MeasureReport) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_type"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TypeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_measure"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.MeasureElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias MeasureReport
	return json.Unmarshal(residual, (*alias)(v))
}

// MeasureReportGroup is a generated nested backbone element.
type MeasureReportGroup struct {
	BackboneElement
	Code         *CodeableConcept               `json:"code,omitempty"`
	Population   []MeasureReportGroupPopulation `json:"population,omitempty"`
	MeasureScore *Quantity                      `json:"measureScore,omitempty"`
	Stratifier   []MeasureReportGroupStratifier `json:"stratifier,omitempty"`
}

// MeasureReportGroupPopulation is a generated nested backbone element.
type MeasureReportGroupPopulation struct {
	BackboneElement
	Code           *CodeableConcept       `json:"code,omitempty"`
	Count          *int32                 `json:"count,omitempty"`
	CountElement   *fhir.PrimitiveElement `json:"-"`
	SubjectResults *Reference             `json:"subjectResults,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v MeasureReportGroupPopulation) MarshalJSON() ([]byte, error) {
	type alias MeasureReportGroupPopulation
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalMeasureReportGroupPopulationSiblings(&v, encoded)
}

// marshalMeasureReportGroupPopulationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalMeasureReportGroupPopulationSiblings(v *MeasureReportGroupPopulation, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.CountElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_count", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *MeasureReportGroupPopulation) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_count"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CountElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias MeasureReportGroupPopulation
	return json.Unmarshal(residual, (*alias)(v))
}

// MeasureReportGroupStratifier is a generated nested backbone element.
type MeasureReportGroupStratifier struct {
	BackboneElement
	Code    []CodeableConcept                     `json:"code,omitempty"`
	Stratum []MeasureReportGroupStratifierStratum `json:"stratum,omitempty"`
}

// MeasureReportGroupStratifierStratum is a generated nested backbone element.
type MeasureReportGroupStratifierStratum struct {
	BackboneElement
	Value        *CodeableConcept                               `json:"value,omitempty"`
	Component    []MeasureReportGroupStratifierStratumComponent `json:"component,omitempty"`
	Population   []MeasureReportGroupPopulation                 `json:"population,omitempty"`
	MeasureScore *Quantity                                      `json:"measureScore,omitempty"`
}

// MeasureReportGroupStratifierStratumComponent is a generated nested backbone element.
type MeasureReportGroupStratifierStratumComponent struct {
	BackboneElement
	Code  *CodeableConcept `json:"code,omitempty"`
	Value *CodeableConcept `json:"value,omitempty"`
}
