// Code generated by fhir-gen; DO NOT EDIT.

package r4

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// PersonResourceType is the FHIR resourceType discriminator for Person.
const PersonResourceType = "Person"

// Person is the generated FHIR Person resource.
type Person struct {
	DomainResource
	Identifier           []Identifier           `json:"identifier,omitempty"`
	Name                 []HumanName            `json:"name,omitempty"`
	Telecom              []ContactPoint         `json:"telecom,omitempty"`
	Gender               *AdministrativeGender  `json:"gender,omitempty"`
	GenderElement        *fhir.PrimitiveElement `json:"-"`
	BirthDate            *string                `json:"birthDate,omitempty"`
	BirthDateElement     *fhir.PrimitiveElement `json:"-"`
	Address              []Address              `json:"address,omitempty"`
	Photo                *Attachment            `json:"photo,omitempty"`
	ManagingOrganization *Reference             `json:"managingOrganization,omitempty"`
	Active               *bool                  `json:"active,omitempty"`
	ActiveElement        *fhir.PrimitiveElement `json:"-"`
	Link                 []PersonLink           `json:"link,omitempty"`
}

// ResourceType returns the FHIR discriminator "Person".
func (r *Person) ResourceType() string { return PersonResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a Person never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *Person) MarshalJSON() ([]byte, error) {
	type alias Person
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: PersonResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalPersonSiblings(r, encoded)
}

// marshalPersonSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalPersonSiblings(v *Person, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.GenderElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_gender", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.BirthDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_birthDate", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ActiveElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_active", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through fhir.UnmarshalResource so the concrete type behind the interface is recovered;
// the standard codec cannot decode a resource object into an interface.
func (v *Person) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_gender"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.GenderElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_birthDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.BirthDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_active"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ActiveElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := fhir.UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias Person
	return json.Unmarshal(residual, (*alias)(v))
}

// PersonLink is a generated nested backbone element.
type PersonLink struct {
	BackboneElement
	Target           *Reference              `json:"target,omitempty"`
	Assurance        *IdentityAssuranceLevel `json:"assurance,omitempty"`
	AssuranceElement *fhir.PrimitiveElement  `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v PersonLink) MarshalJSON() ([]byte, error) {
	type alias PersonLink
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalPersonLinkSiblings(&v, encoded)
}

// marshalPersonLinkSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalPersonLinkSiblings(v *PersonLink, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.AssuranceElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_assurance", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *PersonLink) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_assurance"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.AssuranceElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias PersonLink
	return json.Unmarshal(residual, (*alias)(v))
}
