// Code generated by fhir-gen; DO NOT EDIT.

package r4

// ProductShelfLife is the generated FHIR ProductShelfLife datatype.
type ProductShelfLife struct {
	BackboneElement
	Identifier                   *Identifier       `json:"identifier,omitempty"`
	Type                         *CodeableConcept  `json:"type,omitempty"`
	Period                       *Quantity         `json:"period,omitempty"`
	SpecialPrecautionsForStorage []CodeableConcept `json:"specialPrecautionsForStorage,omitempty"`
}
