// Code generated by fhir-gen; DO NOT EDIT.

package r4

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// ValueSetResourceType is the FHIR resourceType discriminator for ValueSet.
const ValueSetResourceType = "ValueSet"

// ValueSet is the generated FHIR ValueSet resource.
type ValueSet struct {
	DomainResource
	URL                 *string                `json:"url,omitempty"`
	URLElement          *fhir.PrimitiveElement `json:"-"`
	Identifier          []Identifier           `json:"identifier,omitempty"`
	Version             *string                `json:"version,omitempty"`
	VersionElement      *fhir.PrimitiveElement `json:"-"`
	Name                *string                `json:"name,omitempty"`
	NameElement         *fhir.PrimitiveElement `json:"-"`
	Title               *string                `json:"title,omitempty"`
	TitleElement        *fhir.PrimitiveElement `json:"-"`
	Status              *PublicationStatus     `json:"status,omitempty"`
	StatusElement       *fhir.PrimitiveElement `json:"-"`
	Experimental        *bool                  `json:"experimental,omitempty"`
	ExperimentalElement *fhir.PrimitiveElement `json:"-"`
	Date                *string                `json:"date,omitempty"`
	DateElement         *fhir.PrimitiveElement `json:"-"`
	Publisher           *string                `json:"publisher,omitempty"`
	PublisherElement    *fhir.PrimitiveElement `json:"-"`
	Contact             []ContactDetail        `json:"contact,omitempty"`
	Description         *string                `json:"description,omitempty"`
	DescriptionElement  *fhir.PrimitiveElement `json:"-"`
	UseContext          []UsageContext         `json:"useContext,omitempty"`
	Jurisdiction        []CodeableConcept      `json:"jurisdiction,omitempty"`
	Immutable           *bool                  `json:"immutable,omitempty"`
	ImmutableElement    *fhir.PrimitiveElement `json:"-"`
	Purpose             *string                `json:"purpose,omitempty"`
	PurposeElement      *fhir.PrimitiveElement `json:"-"`
	Copyright           *string                `json:"copyright,omitempty"`
	CopyrightElement    *fhir.PrimitiveElement `json:"-"`
	Compose             *ValueSetCompose       `json:"compose,omitempty"`
	Expansion           *ValueSetExpansion     `json:"expansion,omitempty"`
}

// ResourceType returns the FHIR discriminator "ValueSet".
func (r *ValueSet) ResourceType() string { return ValueSetResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a ValueSet never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *ValueSet) MarshalJSON() ([]byte, error) {
	type alias ValueSet
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: ValueSetResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalValueSetSiblings(r, encoded)
}

// marshalValueSetSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalValueSetSiblings(v *ValueSet, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.URLElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_url", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_title", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ExperimentalElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_experimental", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublisherElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publisher", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ImmutableElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_immutable", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PurposeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_purpose", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyright", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through fhir.UnmarshalResource so the concrete type behind the interface is recovered;
// the standard codec cannot decode a resource object into an interface.
func (v *ValueSet) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_url"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URLElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_title"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_experimental"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ExperimentalElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_publisher"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublisherElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_immutable"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ImmutableElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_purpose"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PurposeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyright"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := fhir.UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ValueSet
	return json.Unmarshal(residual, (*alias)(v))
}

// ValueSetCompose is a generated nested backbone element.
type ValueSetCompose struct {
	BackboneElement
	LockedDate        *string                  `json:"lockedDate,omitempty"`
	LockedDateElement *fhir.PrimitiveElement   `json:"-"`
	Inactive          *bool                    `json:"inactive,omitempty"`
	InactiveElement   *fhir.PrimitiveElement   `json:"-"`
	Include           []ValueSetComposeInclude `json:"include,omitempty"`
	Exclude           []ValueSetComposeInclude `json:"exclude,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ValueSetCompose) MarshalJSON() ([]byte, error) {
	type alias ValueSetCompose
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalValueSetComposeSiblings(&v, encoded)
}

// marshalValueSetComposeSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalValueSetComposeSiblings(v *ValueSetCompose, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.LockedDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_lockedDate", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.InactiveElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_inactive", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ValueSetCompose) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_lockedDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.LockedDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_inactive"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.InactiveElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ValueSetCompose
	return json.Unmarshal(residual, (*alias)(v))
}

// ValueSetComposeInclude is a generated nested backbone element.
type ValueSetComposeInclude struct {
	BackboneElement
	System          *string                         `json:"system,omitempty"`
	SystemElement   *fhir.PrimitiveElement          `json:"-"`
	Version         *string                         `json:"version,omitempty"`
	VersionElement  *fhir.PrimitiveElement          `json:"-"`
	Concept         []ValueSetComposeIncludeConcept `json:"concept,omitempty"`
	Filter          []ValueSetComposeIncludeFilter  `json:"filter,omitempty"`
	ValueSet        []string                        `json:"valueSet,omitempty"`
	ValueSetElement []*fhir.PrimitiveElement        `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ValueSetComposeInclude) MarshalJSON() ([]byte, error) {
	type alias ValueSetComposeInclude
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalValueSetComposeIncludeSiblings(&v, encoded)
}

// marshalValueSetComposeIncludeSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalValueSetComposeIncludeSiblings(v *ValueSetComposeInclude, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.SystemElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_system", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.ValueSet), v.ValueSetElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_valueSet", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ValueSetComposeInclude) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_system"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.SystemElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_valueSet"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.ValueSetElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ValueSetComposeInclude
	return json.Unmarshal(residual, (*alias)(v))
}

// ValueSetComposeIncludeConcept is a generated nested backbone element.
type ValueSetComposeIncludeConcept struct {
	BackboneElement
	Code           *string                                    `json:"code,omitempty"`
	CodeElement    *fhir.PrimitiveElement                     `json:"-"`
	Display        *string                                    `json:"display,omitempty"`
	DisplayElement *fhir.PrimitiveElement                     `json:"-"`
	Designation    []ValueSetComposeIncludeConceptDesignation `json:"designation,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ValueSetComposeIncludeConcept) MarshalJSON() ([]byte, error) {
	type alias ValueSetComposeIncludeConcept
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalValueSetComposeIncludeConceptSiblings(&v, encoded)
}

// marshalValueSetComposeIncludeConceptSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalValueSetComposeIncludeConceptSiblings(v *ValueSetComposeIncludeConcept, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.CodeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_code", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DisplayElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_display", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ValueSetComposeIncludeConcept) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_code"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CodeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_display"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DisplayElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ValueSetComposeIncludeConcept
	return json.Unmarshal(residual, (*alias)(v))
}

// ValueSetComposeIncludeConceptDesignation is a generated nested backbone element.
type ValueSetComposeIncludeConceptDesignation struct {
	BackboneElement
	Language        *string                `json:"language,omitempty"`
	LanguageElement *fhir.PrimitiveElement `json:"-"`
	Use             *Coding                `json:"use,omitempty"`
	Value           *string                `json:"value,omitempty"`
	ValueElement    *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ValueSetComposeIncludeConceptDesignation) MarshalJSON() ([]byte, error) {
	type alias ValueSetComposeIncludeConceptDesignation
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalValueSetComposeIncludeConceptDesignationSiblings(&v, encoded)
}

// marshalValueSetComposeIncludeConceptDesignationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalValueSetComposeIncludeConceptDesignationSiblings(v *ValueSetComposeIncludeConceptDesignation, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.LanguageElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_language", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ValueElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_value", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ValueSetComposeIncludeConceptDesignation) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_language"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.LanguageElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_value"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ValueElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ValueSetComposeIncludeConceptDesignation
	return json.Unmarshal(residual, (*alias)(v))
}

// ValueSetComposeIncludeFilter is a generated nested backbone element.
type ValueSetComposeIncludeFilter struct {
	BackboneElement
	Property        *string                `json:"property,omitempty"`
	PropertyElement *fhir.PrimitiveElement `json:"-"`
	Op              *FilterOperator        `json:"op,omitempty"`
	OpElement       *fhir.PrimitiveElement `json:"-"`
	Value           *string                `json:"value,omitempty"`
	ValueElement    *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ValueSetComposeIncludeFilter) MarshalJSON() ([]byte, error) {
	type alias ValueSetComposeIncludeFilter
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalValueSetComposeIncludeFilterSiblings(&v, encoded)
}

// marshalValueSetComposeIncludeFilterSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalValueSetComposeIncludeFilterSiblings(v *ValueSetComposeIncludeFilter, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.PropertyElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_property", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.OpElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_op", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ValueElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_value", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ValueSetComposeIncludeFilter) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_property"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PropertyElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_op"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.OpElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_value"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ValueElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ValueSetComposeIncludeFilter
	return json.Unmarshal(residual, (*alias)(v))
}

// ValueSetExpansion is a generated nested backbone element.
type ValueSetExpansion struct {
	BackboneElement
	Identifier        *string                      `json:"identifier,omitempty"`
	IdentifierElement *fhir.PrimitiveElement       `json:"-"`
	Timestamp         *string                      `json:"timestamp,omitempty"`
	TimestampElement  *fhir.PrimitiveElement       `json:"-"`
	Total             *int32                       `json:"total,omitempty"`
	TotalElement      *fhir.PrimitiveElement       `json:"-"`
	Offset            *int32                       `json:"offset,omitempty"`
	OffsetElement     *fhir.PrimitiveElement       `json:"-"`
	Parameter         []ValueSetExpansionParameter `json:"parameter,omitempty"`
	Contains          []ValueSetExpansionContains  `json:"contains,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ValueSetExpansion) MarshalJSON() ([]byte, error) {
	type alias ValueSetExpansion
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalValueSetExpansionSiblings(&v, encoded)
}

// marshalValueSetExpansionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalValueSetExpansionSiblings(v *ValueSetExpansion, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.IdentifierElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_identifier", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TimestampElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_timestamp", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TotalElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_total", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.OffsetElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_offset", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ValueSetExpansion) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_identifier"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.IdentifierElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_timestamp"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TimestampElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_total"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TotalElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_offset"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.OffsetElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ValueSetExpansion
	return json.Unmarshal(residual, (*alias)(v))
}

// ValueSetExpansionContains is a generated nested backbone element.
type ValueSetExpansionContains struct {
	BackboneElement
	System          *string                                    `json:"system,omitempty"`
	SystemElement   *fhir.PrimitiveElement                     `json:"-"`
	Abstract        *bool                                      `json:"abstract,omitempty"`
	AbstractElement *fhir.PrimitiveElement                     `json:"-"`
	Inactive        *bool                                      `json:"inactive,omitempty"`
	InactiveElement *fhir.PrimitiveElement                     `json:"-"`
	Version         *string                                    `json:"version,omitempty"`
	VersionElement  *fhir.PrimitiveElement                     `json:"-"`
	Code            *string                                    `json:"code,omitempty"`
	CodeElement     *fhir.PrimitiveElement                     `json:"-"`
	Display         *string                                    `json:"display,omitempty"`
	DisplayElement  *fhir.PrimitiveElement                     `json:"-"`
	Designation     []ValueSetComposeIncludeConceptDesignation `json:"designation,omitempty"`
	Contains        []ValueSetExpansionContains                `json:"contains,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ValueSetExpansionContains) MarshalJSON() ([]byte, error) {
	type alias ValueSetExpansionContains
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalValueSetExpansionContainsSiblings(&v, encoded)
}

// marshalValueSetExpansionContainsSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalValueSetExpansionContainsSiblings(v *ValueSetExpansionContains, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.SystemElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_system", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.AbstractElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_abstract", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.InactiveElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_inactive", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CodeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_code", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DisplayElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_display", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ValueSetExpansionContains) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_system"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.SystemElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_abstract"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.AbstractElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_inactive"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.InactiveElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_code"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CodeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_display"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DisplayElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ValueSetExpansionContains
	return json.Unmarshal(residual, (*alias)(v))
}

// ValueSetExpansionParameter is a generated nested backbone element.
type ValueSetExpansionParameter struct {
	BackboneElement
	Name          *string                `json:"name,omitempty"`
	NameElement   *fhir.PrimitiveElement `json:"-"`
	ValueString   *FHIRString            `json:"valueString,omitempty"`
	ValueBoolean  *FHIRBoolean           `json:"valueBoolean,omitempty"`
	ValueInteger  *FHIRInteger           `json:"valueInteger,omitempty"`
	ValueDecimal  *FHIRDecimal           `json:"valueDecimal,omitempty"`
	ValueURI      *FHIRURI               `json:"valueUri,omitempty"`
	ValueCode     *FHIRCode              `json:"valueCode,omitempty"`
	ValueDateTime *FHIRDateTime          `json:"valueDateTime,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ValueSetExpansionParameter) MarshalJSON() ([]byte, error) {
	type alias ValueSetExpansionParameter
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalValueSetExpansionParameterSiblings(&v, encoded)
}

// marshalValueSetExpansionParameterSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalValueSetExpansionParameterSiblings(v *ValueSetExpansionParameter, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ValueSetExpansionParameter) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ValueSetExpansionParameter
	return json.Unmarshal(residual, (*alias)(v))
}

// ValueSetExpansionParameterValue is the sealed value interface for the value[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isValueSetExpansionParameterValue marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type ValueSetExpansionParameterValue interface{ isValueSetExpansionParameterValue() }

func (FHIRString) isValueSetExpansionParameterValue()   {}
func (FHIRBoolean) isValueSetExpansionParameterValue()  {}
func (FHIRInteger) isValueSetExpansionParameterValue()  {}
func (FHIRDecimal) isValueSetExpansionParameterValue()  {}
func (FHIRURI) isValueSetExpansionParameterValue()      {}
func (FHIRCode) isValueSetExpansionParameterValue()     {}
func (FHIRDateTime) isValueSetExpansionParameterValue() {}

// Value returns the value set in the value[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *ValueSetExpansionParameter) Value() (ValueSetExpansionParameterValue, bool) {
	switch {
	case r.ValueString != nil:
		return *r.ValueString, true
	case r.ValueBoolean != nil:
		return *r.ValueBoolean, true
	case r.ValueInteger != nil:
		return *r.ValueInteger, true
	case r.ValueDecimal != nil:
		return *r.ValueDecimal, true
	case r.ValueURI != nil:
		return *r.ValueURI, true
	case r.ValueCode != nil:
		return *r.ValueCode, true
	case r.ValueDateTime != nil:
		return *r.ValueDateTime, true
	}
	return nil, false
}

// SetValueString sets value[x] to a FHIRString (the
// release primitive wrapper that carries the isValueSetExpansionParameterValue marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *ValueSetExpansionParameter) SetValueString(v FHIRString) {
	r.ValueString = nil
	r.ValueBoolean = nil
	r.ValueInteger = nil
	r.ValueDecimal = nil
	r.ValueURI = nil
	r.ValueCode = nil
	r.ValueDateTime = nil
	r.ValueString = &v
}

// SetValueBoolean sets value[x] to a FHIRBoolean (the
// release primitive wrapper that carries the isValueSetExpansionParameterValue marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *ValueSetExpansionParameter) SetValueBoolean(v FHIRBoolean) {
	r.ValueString = nil
	r.ValueBoolean = nil
	r.ValueInteger = nil
	r.ValueDecimal = nil
	r.ValueURI = nil
	r.ValueCode = nil
	r.ValueDateTime = nil
	r.ValueBoolean = &v
}

// SetValueInteger sets value[x] to a FHIRInteger (the
// release primitive wrapper that carries the isValueSetExpansionParameterValue marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *ValueSetExpansionParameter) SetValueInteger(v FHIRInteger) {
	r.ValueString = nil
	r.ValueBoolean = nil
	r.ValueInteger = nil
	r.ValueDecimal = nil
	r.ValueURI = nil
	r.ValueCode = nil
	r.ValueDateTime = nil
	r.ValueInteger = &v
}

// SetValueDecimal sets value[x] to a FHIRDecimal (the
// release primitive wrapper that carries the isValueSetExpansionParameterValue marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *ValueSetExpansionParameter) SetValueDecimal(v FHIRDecimal) {
	r.ValueString = nil
	r.ValueBoolean = nil
	r.ValueInteger = nil
	r.ValueDecimal = nil
	r.ValueURI = nil
	r.ValueCode = nil
	r.ValueDateTime = nil
	r.ValueDecimal = &v
}

// SetValueURI sets value[x] to a FHIRURI (the
// release primitive wrapper that carries the isValueSetExpansionParameterValue marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *ValueSetExpansionParameter) SetValueURI(v FHIRURI) {
	r.ValueString = nil
	r.ValueBoolean = nil
	r.ValueInteger = nil
	r.ValueDecimal = nil
	r.ValueURI = nil
	r.ValueCode = nil
	r.ValueDateTime = nil
	r.ValueURI = &v
}

// SetValueCode sets value[x] to a FHIRCode (the
// release primitive wrapper that carries the isValueSetExpansionParameterValue marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *ValueSetExpansionParameter) SetValueCode(v FHIRCode) {
	r.ValueString = nil
	r.ValueBoolean = nil
	r.ValueInteger = nil
	r.ValueDecimal = nil
	r.ValueURI = nil
	r.ValueCode = nil
	r.ValueDateTime = nil
	r.ValueCode = &v
}

// SetValueDateTime sets value[x] to a FHIRDateTime (the
// release primitive wrapper that carries the isValueSetExpansionParameterValue marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *ValueSetExpansionParameter) SetValueDateTime(v FHIRDateTime) {
	r.ValueString = nil
	r.ValueBoolean = nil
	r.ValueInteger = nil
	r.ValueDecimal = nil
	r.ValueURI = nil
	r.ValueCode = nil
	r.ValueDateTime = nil
	r.ValueDateTime = &v
}
