version: 2

run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck        # Check for unchecked errors
    - govet           # Vet examines Go source code
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Staticcheck is go vet on steroids
    - unused          # Check for unused code
    - misspell        # Check for commonly misspelled English words
    - revive          # Fast, configurable, extensible, flexible linter
    - gosec           # Security-focused linter
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Check for unused function parameters
    - prealloc        # Find slice declarations with non-zero initial length
    - gocritic        # The most opinionated Go linter
    - gocyclo         # Cyclomatic complexity
    - bodyclose       # Check HTTP response body is closed
    - nolintlint      # Ensure nolint directives are properly formatted

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow  # Can be too noisy for some codebases

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult  # Allow unnamed returns for short functions
      - hugeParam      # May flag FHIR/DICOM structs with many fields

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  misspell:
    locale: US

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - gocritic
        - revive

    # Exclude example code from strict checks
    - path: "fhir/examples/.*\\.go$"
      linters:
        - errcheck
        - gosec

    # Exclude linters for generated FHIR resource files
    - path: "fhir/r[45]/resources/.*\\.go$"
      linters:
        - gocyclo
        - revive
        - gocritic
        - funlen
        - misspell

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
