// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// CitationResourceType is the FHIR resourceType discriminator for Citation.
const CitationResourceType = "Citation"

// Citation is the generated FHIR Citation resource.
type Citation struct {
	DomainResource
	URL                    *string                  `json:"url,omitempty"`
	URLElement             *fhir.PrimitiveElement   `json:"-"`
	Identifier             []Identifier             `json:"identifier,omitempty"`
	Version                *string                  `json:"version,omitempty"`
	VersionElement         *fhir.PrimitiveElement   `json:"-"`
	VersionAlgorithmString *FHIRString              `json:"versionAlgorithmString,omitempty"`
	VersionAlgorithmCoding *Coding                  `json:"versionAlgorithmCoding,omitempty"`
	Name                   *string                  `json:"name,omitempty"`
	NameElement            *fhir.PrimitiveElement   `json:"-"`
	Title                  *string                  `json:"title,omitempty"`
	TitleElement           *fhir.PrimitiveElement   `json:"-"`
	Status                 *PublicationStatus       `json:"status,omitempty"`
	StatusElement          *fhir.PrimitiveElement   `json:"-"`
	Experimental           *bool                    `json:"experimental,omitempty"`
	ExperimentalElement    *fhir.PrimitiveElement   `json:"-"`
	Date                   *string                  `json:"date,omitempty"`
	DateElement            *fhir.PrimitiveElement   `json:"-"`
	Publisher              *string                  `json:"publisher,omitempty"`
	PublisherElement       *fhir.PrimitiveElement   `json:"-"`
	Contact                []ContactDetail          `json:"contact,omitempty"`
	Description            *string                  `json:"description,omitempty"`
	DescriptionElement     *fhir.PrimitiveElement   `json:"-"`
	UseContext             []UsageContext           `json:"useContext,omitempty"`
	Jurisdiction           []CodeableConcept        `json:"jurisdiction,omitempty"`
	Purpose                *string                  `json:"purpose,omitempty"`
	PurposeElement         *fhir.PrimitiveElement   `json:"-"`
	Copyright              *string                  `json:"copyright,omitempty"`
	CopyrightElement       *fhir.PrimitiveElement   `json:"-"`
	CopyrightLabel         *string                  `json:"copyrightLabel,omitempty"`
	CopyrightLabelElement  *fhir.PrimitiveElement   `json:"-"`
	ApprovalDate           *string                  `json:"approvalDate,omitempty"`
	ApprovalDateElement    *fhir.PrimitiveElement   `json:"-"`
	LastReviewDate         *string                  `json:"lastReviewDate,omitempty"`
	LastReviewDateElement  *fhir.PrimitiveElement   `json:"-"`
	EffectivePeriod        *Period                  `json:"effectivePeriod,omitempty"`
	Author                 []ContactDetail          `json:"author,omitempty"`
	Editor                 []ContactDetail          `json:"editor,omitempty"`
	Reviewer               []ContactDetail          `json:"reviewer,omitempty"`
	Endorser               []ContactDetail          `json:"endorser,omitempty"`
	Summary                []CitationSummary        `json:"summary,omitempty"`
	Classification         []CitationClassification `json:"classification,omitempty"`
	Note                   []Annotation             `json:"note,omitempty"`
	CurrentState           []CodeableConcept        `json:"currentState,omitempty"`
	StatusDate             []CitationStatusDate     `json:"statusDate,omitempty"`
	RelatedArtifact        []RelatedArtifact        `json:"relatedArtifact,omitempty"`
	CitedArtifact          *CitationCitedArtifact   `json:"citedArtifact,omitempty"`
}

// ResourceType returns the FHIR discriminator "Citation".
func (r *Citation) ResourceType() string { return CitationResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a Citation never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *Citation) MarshalJSON() ([]byte, error) {
	type alias Citation
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: CitationResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalCitationSiblings(r, encoded)
}

// marshalCitationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationSiblings(v *Citation, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.URLElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_url", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_title", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ExperimentalElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_experimental", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublisherElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publisher", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PurposeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_purpose", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyright", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightLabelElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyrightLabel", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ApprovalDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_approvalDate", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.LastReviewDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_lastReviewDate", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through fhir.UnmarshalResource so the concrete type behind the interface is recovered;
// the standard codec cannot decode a resource object into an interface.
func (v *Citation) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_url"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URLElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_title"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_experimental"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ExperimentalElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_publisher"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublisherElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_purpose"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PurposeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyright"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyrightLabel"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightLabelElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_approvalDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ApprovalDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_lastReviewDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.LastReviewDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := fhir.UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias Citation
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationVersionAlgorithm is the sealed value interface for the versionAlgorithm[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isCitationVersionAlgorithm marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type CitationVersionAlgorithm interface{ isCitationVersionAlgorithm() }

func (FHIRString) isCitationVersionAlgorithm() {}
func (Coding) isCitationVersionAlgorithm()     {}

// VersionAlgorithm returns the value set in the versionAlgorithm[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *Citation) VersionAlgorithm() (CitationVersionAlgorithm, bool) {
	switch {
	case r.VersionAlgorithmString != nil:
		return *r.VersionAlgorithmString, true
	case r.VersionAlgorithmCoding != nil:
		return *r.VersionAlgorithmCoding, true
	}
	return nil, false
}

// SetVersionAlgorithmString sets versionAlgorithm[x] to a FHIRString (the
// release primitive wrapper that carries the isCitationVersionAlgorithm marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *Citation) SetVersionAlgorithmString(v FHIRString) {
	r.VersionAlgorithmString = nil
	r.VersionAlgorithmCoding = nil
	r.VersionAlgorithmString = &v
}

// SetVersionAlgorithmCoding sets versionAlgorithm[x] to a Coding and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *Citation) SetVersionAlgorithmCoding(v Coding) {
	r.VersionAlgorithmString = nil
	r.VersionAlgorithmCoding = nil
	r.VersionAlgorithmCoding = &v
}

// CitationCitedArtifact is a generated nested backbone element.
type CitationCitedArtifact struct {
	BackboneElement
	Identifier          []Identifier                           `json:"identifier,omitempty"`
	RelatedIdentifier   []Identifier                           `json:"relatedIdentifier,omitempty"`
	DateAccessed        *string                                `json:"dateAccessed,omitempty"`
	DateAccessedElement *fhir.PrimitiveElement                 `json:"-"`
	Version             *CitationCitedArtifactVersion          `json:"version,omitempty"`
	CurrentState        []CodeableConcept                      `json:"currentState,omitempty"`
	StatusDate          []CitationStatusDate                   `json:"statusDate,omitempty"`
	Title               []CitationCitedArtifactTitle           `json:"title,omitempty"`
	Abstract            []CitationCitedArtifactAbstract        `json:"abstract,omitempty"`
	Part                *CitationCitedArtifactPart             `json:"part,omitempty"`
	RelatesTo           []CitationCitedArtifactRelatesTo       `json:"relatesTo,omitempty"`
	PublicationForm     []CitationCitedArtifactPublicationForm `json:"publicationForm,omitempty"`
	WebLocation         []CitationCitedArtifactWebLocation     `json:"webLocation,omitempty"`
	Classification      []CitationCitedArtifactClassification  `json:"classification,omitempty"`
	Contributorship     *CitationCitedArtifactContributorship  `json:"contributorship,omitempty"`
	Note                []Annotation                           `json:"note,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifact) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifact
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactSiblings(&v, encoded)
}

// marshalCitationCitedArtifactSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactSiblings(v *CitationCitedArtifact, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateAccessedElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_dateAccessed", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifact) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_dateAccessed"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateAccessedElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifact
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactAbstract is a generated nested backbone element.
type CitationCitedArtifactAbstract struct {
	BackboneElement
	Type             *CodeableConcept       `json:"type,omitempty"`
	Language         *CodeableConcept       `json:"language,omitempty"`
	Text             *string                `json:"text,omitempty"`
	TextElement      *fhir.PrimitiveElement `json:"-"`
	Copyright        *string                `json:"copyright,omitempty"`
	CopyrightElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactAbstract) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactAbstract
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactAbstractSiblings(&v, encoded)
}

// marshalCitationCitedArtifactAbstractSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactAbstractSiblings(v *CitationCitedArtifactAbstract, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TextElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_text", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyright", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactAbstract) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_text"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TextElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyright"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactAbstract
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactClassification is a generated nested backbone element.
type CitationCitedArtifactClassification struct {
	BackboneElement
	Type               *CodeableConcept  `json:"type,omitempty"`
	Classifier         []CodeableConcept `json:"classifier,omitempty"`
	ArtifactAssessment []Reference       `json:"artifactAssessment,omitempty"`
}

// CitationCitedArtifactContributorship is a generated nested backbone element.
type CitationCitedArtifactContributorship struct {
	BackboneElement
	Complete        *bool                                         `json:"complete,omitempty"`
	CompleteElement *fhir.PrimitiveElement                        `json:"-"`
	Entry           []CitationCitedArtifactContributorshipEntry   `json:"entry,omitempty"`
	Summary         []CitationCitedArtifactContributorshipSummary `json:"summary,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactContributorship) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactContributorship
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactContributorshipSiblings(&v, encoded)
}

// marshalCitationCitedArtifactContributorshipSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactContributorshipSiblings(v *CitationCitedArtifactContributorship, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.CompleteElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_complete", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactContributorship) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_complete"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CompleteElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactContributorship
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactContributorshipEntry is a generated nested backbone element.
type CitationCitedArtifactContributorshipEntry struct {
	BackboneElement
	Contributor                 *Reference                                                      `json:"contributor,omitempty"`
	ForenameInitials            *string                                                         `json:"forenameInitials,omitempty"`
	ForenameInitialsElement     *fhir.PrimitiveElement                                          `json:"-"`
	Affiliation                 []Reference                                                     `json:"affiliation,omitempty"`
	ContributionType            []CodeableConcept                                               `json:"contributionType,omitempty"`
	Role                        *CodeableConcept                                                `json:"role,omitempty"`
	ContributionInstance        []CitationCitedArtifactContributorshipEntryContributionInstance `json:"contributionInstance,omitempty"`
	CorrespondingContact        *bool                                                           `json:"correspondingContact,omitempty"`
	CorrespondingContactElement *fhir.PrimitiveElement                                          `json:"-"`
	RankingOrder                *int32                                                          `json:"rankingOrder,omitempty"`
	RankingOrderElement         *fhir.PrimitiveElement                                          `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactContributorshipEntry) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactContributorshipEntry
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactContributorshipEntrySiblings(&v, encoded)
}

// marshalCitationCitedArtifactContributorshipEntrySiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactContributorshipEntrySiblings(v *CitationCitedArtifactContributorshipEntry, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.ForenameInitialsElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_forenameInitials", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CorrespondingContactElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_correspondingContact", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.RankingOrderElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_rankingOrder", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactContributorshipEntry) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_forenameInitials"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ForenameInitialsElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_correspondingContact"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CorrespondingContactElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_rankingOrder"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.RankingOrderElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactContributorshipEntry
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactContributorshipEntryContributionInstance is a generated nested backbone element.
type CitationCitedArtifactContributorshipEntryContributionInstance struct {
	BackboneElement
	Type        *CodeableConcept       `json:"type,omitempty"`
	Time        *string                `json:"time,omitempty"`
	TimeElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactContributorshipEntryContributionInstance) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactContributorshipEntryContributionInstance
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactContributorshipEntryContributionInstanceSiblings(&v, encoded)
}

// marshalCitationCitedArtifactContributorshipEntryContributionInstanceSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactContributorshipEntryContributionInstanceSiblings(v *CitationCitedArtifactContributorshipEntryContributionInstance, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TimeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_time", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactContributorshipEntryContributionInstance) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_time"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TimeElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactContributorshipEntryContributionInstance
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactContributorshipSummary is a generated nested backbone element.
type CitationCitedArtifactContributorshipSummary struct {
	BackboneElement
	Type         *CodeableConcept       `json:"type,omitempty"`
	Style        *CodeableConcept       `json:"style,omitempty"`
	Source       *CodeableConcept       `json:"source,omitempty"`
	Value        *string                `json:"value,omitempty"`
	ValueElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactContributorshipSummary) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactContributorshipSummary
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactContributorshipSummarySiblings(&v, encoded)
}

// marshalCitationCitedArtifactContributorshipSummarySiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactContributorshipSummarySiblings(v *CitationCitedArtifactContributorshipSummary, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.ValueElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_value", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactContributorshipSummary) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_value"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ValueElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactContributorshipSummary
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactPart is a generated nested backbone element.
type CitationCitedArtifactPart struct {
	BackboneElement
	Type         *CodeableConcept       `json:"type,omitempty"`
	Value        *string                `json:"value,omitempty"`
	ValueElement *fhir.PrimitiveElement `json:"-"`
	BaseCitation *Reference             `json:"baseCitation,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactPart) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactPart
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactPartSiblings(&v, encoded)
}

// marshalCitationCitedArtifactPartSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactPartSiblings(v *CitationCitedArtifactPart, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.ValueElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_value", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactPart) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_value"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ValueElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactPart
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactPublicationForm is a generated nested backbone element.
type CitationCitedArtifactPublicationForm struct {
	BackboneElement
	PublishedIn                  *CitationCitedArtifactPublicationFormPublishedIn `json:"publishedIn,omitempty"`
	CitedMedium                  *CodeableConcept                                 `json:"citedMedium,omitempty"`
	Volume                       *string                                          `json:"volume,omitempty"`
	VolumeElement                *fhir.PrimitiveElement                           `json:"-"`
	Issue                        *string                                          `json:"issue,omitempty"`
	IssueElement                 *fhir.PrimitiveElement                           `json:"-"`
	ArticleDate                  *string                                          `json:"articleDate,omitempty"`
	ArticleDateElement           *fhir.PrimitiveElement                           `json:"-"`
	PublicationDateText          *string                                          `json:"publicationDateText,omitempty"`
	PublicationDateTextElement   *fhir.PrimitiveElement                           `json:"-"`
	PublicationDateSeason        *string                                          `json:"publicationDateSeason,omitempty"`
	PublicationDateSeasonElement *fhir.PrimitiveElement                           `json:"-"`
	LastRevisionDate             *string                                          `json:"lastRevisionDate,omitempty"`
	LastRevisionDateElement      *fhir.PrimitiveElement                           `json:"-"`
	Language                     []CodeableConcept                                `json:"language,omitempty"`
	AccessionNumber              *string                                          `json:"accessionNumber,omitempty"`
	AccessionNumberElement       *fhir.PrimitiveElement                           `json:"-"`
	PageString                   *string                                          `json:"pageString,omitempty"`
	PageStringElement            *fhir.PrimitiveElement                           `json:"-"`
	FirstPage                    *string                                          `json:"firstPage,omitempty"`
	FirstPageElement             *fhir.PrimitiveElement                           `json:"-"`
	LastPage                     *string                                          `json:"lastPage,omitempty"`
	LastPageElement              *fhir.PrimitiveElement                           `json:"-"`
	PageCount                    *string                                          `json:"pageCount,omitempty"`
	PageCountElement             *fhir.PrimitiveElement                           `json:"-"`
	Copyright                    *string                                          `json:"copyright,omitempty"`
	CopyrightElement             *fhir.PrimitiveElement                           `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactPublicationForm) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactPublicationForm
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactPublicationFormSiblings(&v, encoded)
}

// marshalCitationCitedArtifactPublicationFormSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactPublicationFormSiblings(v *CitationCitedArtifactPublicationForm, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.VolumeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_volume", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.IssueElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_issue", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ArticleDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_articleDate", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublicationDateTextElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publicationDateText", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublicationDateSeasonElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publicationDateSeason", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.LastRevisionDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_lastRevisionDate", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.AccessionNumberElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_accessionNumber", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PageStringElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_pageString", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.FirstPageElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_firstPage", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.LastPageElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_lastPage", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PageCountElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_pageCount", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyright", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactPublicationForm) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_volume"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VolumeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_issue"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.IssueElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_articleDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ArticleDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_publicationDateText"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublicationDateTextElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_publicationDateSeason"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublicationDateSeasonElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_lastRevisionDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.LastRevisionDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_accessionNumber"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.AccessionNumberElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_pageString"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PageStringElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_firstPage"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.FirstPageElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_lastPage"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.LastPageElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_pageCount"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PageCountElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyright"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactPublicationForm
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactPublicationFormPublishedIn is a generated nested backbone element.
type CitationCitedArtifactPublicationFormPublishedIn struct {
	BackboneElement
	Type                     *CodeableConcept       `json:"type,omitempty"`
	Identifier               []Identifier           `json:"identifier,omitempty"`
	Title                    *string                `json:"title,omitempty"`
	TitleElement             *fhir.PrimitiveElement `json:"-"`
	Publisher                *Reference             `json:"publisher,omitempty"`
	PublisherLocation        *string                `json:"publisherLocation,omitempty"`
	PublisherLocationElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactPublicationFormPublishedIn) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactPublicationFormPublishedIn
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactPublicationFormPublishedInSiblings(&v, encoded)
}

// marshalCitationCitedArtifactPublicationFormPublishedInSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactPublicationFormPublishedInSiblings(v *CitationCitedArtifactPublicationFormPublishedIn, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_title", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublisherLocationElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publisherLocation", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactPublicationFormPublishedIn) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_title"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_publisherLocation"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublisherLocationElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactPublicationFormPublishedIn
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactRelatesTo is a generated nested backbone element.
type CitationCitedArtifactRelatesTo struct {
	BackboneElement
	Type              *RelatedArtifactTypeExpanded `json:"type,omitempty"`
	TypeElement       *fhir.PrimitiveElement       `json:"-"`
	Classifier        []CodeableConcept            `json:"classifier,omitempty"`
	Label             *string                      `json:"label,omitempty"`
	LabelElement      *fhir.PrimitiveElement       `json:"-"`
	Display           *string                      `json:"display,omitempty"`
	DisplayElement    *fhir.PrimitiveElement       `json:"-"`
	Citation          *string                      `json:"citation,omitempty"`
	CitationElement   *fhir.PrimitiveElement       `json:"-"`
	Document          *Attachment                  `json:"document,omitempty"`
	Resource          *string                      `json:"resource,omitempty"`
	ResourceElement   *fhir.PrimitiveElement       `json:"-"`
	ResourceReference *Reference                   `json:"resourceReference,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactRelatesTo) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactRelatesTo
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactRelatesToSiblings(&v, encoded)
}

// marshalCitationCitedArtifactRelatesToSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactRelatesToSiblings(v *CitationCitedArtifactRelatesTo, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TypeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_type", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.LabelElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_label", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DisplayElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_display", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CitationElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_citation", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ResourceElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_resource", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactRelatesTo) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_type"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TypeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_label"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.LabelElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_display"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DisplayElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_citation"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CitationElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_resource"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ResourceElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactRelatesTo
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactTitle is a generated nested backbone element.
type CitationCitedArtifactTitle struct {
	BackboneElement
	Type        []CodeableConcept      `json:"type,omitempty"`
	Language    *CodeableConcept       `json:"language,omitempty"`
	Text        *string                `json:"text,omitempty"`
	TextElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactTitle) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactTitle
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactTitleSiblings(&v, encoded)
}

// marshalCitationCitedArtifactTitleSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactTitleSiblings(v *CitationCitedArtifactTitle, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TextElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_text", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactTitle) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_text"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TextElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactTitle
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactVersion is a generated nested backbone element.
type CitationCitedArtifactVersion struct {
	BackboneElement
	Value        *string                `json:"value,omitempty"`
	ValueElement *fhir.PrimitiveElement `json:"-"`
	BaseCitation *Reference             `json:"baseCitation,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactVersion) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactVersion
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactVersionSiblings(&v, encoded)
}

// marshalCitationCitedArtifactVersionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactVersionSiblings(v *CitationCitedArtifactVersion, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.ValueElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_value", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactVersion) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_value"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ValueElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactVersion
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationCitedArtifactWebLocation is a generated nested backbone element.
type CitationCitedArtifactWebLocation struct {
	BackboneElement
	Classifier []CodeableConcept      `json:"classifier,omitempty"`
	URL        *string                `json:"url,omitempty"`
	URLElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationCitedArtifactWebLocation) MarshalJSON() ([]byte, error) {
	type alias CitationCitedArtifactWebLocation
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationCitedArtifactWebLocationSiblings(&v, encoded)
}

// marshalCitationCitedArtifactWebLocationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationCitedArtifactWebLocationSiblings(v *CitationCitedArtifactWebLocation, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.URLElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_url", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationCitedArtifactWebLocation) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_url"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URLElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationCitedArtifactWebLocation
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationClassification is a generated nested backbone element.
type CitationClassification struct {
	BackboneElement
	Type       *CodeableConcept  `json:"type,omitempty"`
	Classifier []CodeableConcept `json:"classifier,omitempty"`
}

// CitationStatusDate is a generated nested backbone element.
type CitationStatusDate struct {
	BackboneElement
	Activity      *CodeableConcept       `json:"activity,omitempty"`
	Actual        *bool                  `json:"actual,omitempty"`
	ActualElement *fhir.PrimitiveElement `json:"-"`
	Period        *Period                `json:"period,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationStatusDate) MarshalJSON() ([]byte, error) {
	type alias CitationStatusDate
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationStatusDateSiblings(&v, encoded)
}

// marshalCitationStatusDateSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationStatusDateSiblings(v *CitationStatusDate, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.ActualElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_actual", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationStatusDate) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_actual"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ActualElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationStatusDate
	return json.Unmarshal(residual, (*alias)(v))
}

// CitationSummary is a generated nested backbone element.
type CitationSummary struct {
	BackboneElement
	Style       *CodeableConcept       `json:"style,omitempty"`
	Text        *string                `json:"text,omitempty"`
	TextElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CitationSummary) MarshalJSON() ([]byte, error) {
	type alias CitationSummary
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCitationSummarySiblings(&v, encoded)
}

// marshalCitationSummarySiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCitationSummarySiblings(v *CitationSummary, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TextElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_text", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CitationSummary) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_text"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TextElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CitationSummary
	return json.Unmarshal(residual, (*alias)(v))
}
