// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// Coding is the generated FHIR Coding datatype.
type Coding struct {
	Element
	System              *string                `json:"system,omitempty"`
	SystemElement       *fhir.PrimitiveElement `json:"-"`
	Version             *string                `json:"version,omitempty"`
	VersionElement      *fhir.PrimitiveElement `json:"-"`
	Code                *string                `json:"code,omitempty"`
	CodeElement         *fhir.PrimitiveElement `json:"-"`
	Display             *string                `json:"display,omitempty"`
	DisplayElement      *fhir.PrimitiveElement `json:"-"`
	UserSelected        *bool                  `json:"userSelected,omitempty"`
	UserSelectedElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the primitive "_field" siblings into the encoded value: a scalar
// sibling is dropped when it carries no id or extension, and a repeating sibling's
// array is null-aligned with its value array, so a partially-extended repeating
// primitive lines up position-for-position on the wire (a position with no
// id/extension becomes a JSON null in the "_field" array).
func (v Coding) MarshalJSON() ([]byte, error) {
	type alias Coding
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCodingSiblings(&v, encoded)
}

// marshalCodingSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCodingSiblings(v *Coding, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.SystemElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_system", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CodeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_code", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DisplayElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_display", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.UserSelectedElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_userSelected", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *Coding) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_system"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.SystemElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_code"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CodeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_display"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DisplayElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_userSelected"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.UserSelectedElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias Coding
	return json.Unmarshal(residual, (*alias)(v))
}
