// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// CompositionResourceType is the FHIR resourceType discriminator for Composition.
const CompositionResourceType = "Composition"

// Composition is the generated FHIR Composition resource.
type Composition struct {
	DomainResource
	URL            *string                `json:"url,omitempty"`
	URLElement     *fhir.PrimitiveElement `json:"-"`
	Identifier     []Identifier           `json:"identifier,omitempty"`
	Version        *string                `json:"version,omitempty"`
	VersionElement *fhir.PrimitiveElement `json:"-"`
	Status         *CompositionStatus     `json:"status,omitempty"`
	StatusElement  *fhir.PrimitiveElement `json:"-"`
	Type           *CodeableConcept       `json:"type,omitempty"`
	Category       []CodeableConcept      `json:"category,omitempty"`
	Subject        []Reference            `json:"subject,omitempty"`
	Encounter      *Reference             `json:"encounter,omitempty"`
	Date           *string                `json:"date,omitempty"`
	DateElement    *fhir.PrimitiveElement `json:"-"`
	UseContext     []UsageContext         `json:"useContext,omitempty"`
	Author         []Reference            `json:"author,omitempty"`
	Name           *string                `json:"name,omitempty"`
	NameElement    *fhir.PrimitiveElement `json:"-"`
	Title          *string                `json:"title,omitempty"`
	TitleElement   *fhir.PrimitiveElement `json:"-"`
	Note           []Annotation           `json:"note,omitempty"`
	Attester       []CompositionAttester  `json:"attester,omitempty"`
	Custodian      *Reference             `json:"custodian,omitempty"`
	RelatesTo      []RelatedArtifact      `json:"relatesTo,omitempty"`
	Event          []CompositionEvent     `json:"event,omitempty"`
	Section        []CompositionSection   `json:"section,omitempty"`
}

// ResourceType returns the FHIR discriminator "Composition".
func (r *Composition) ResourceType() string { return CompositionResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a Composition never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *Composition) MarshalJSON() ([]byte, error) {
	type alias Composition
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: CompositionResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalCompositionSiblings(r, encoded)
}

// marshalCompositionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCompositionSiblings(v *Composition, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.URLElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_url", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_title", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through the release-local UnmarshalResource so the concrete type behind the interface
// is recovered as a resource of this release; the standard codec cannot decode a resource
// object into an interface.
func (v *Composition) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_url"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URLElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_title"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias Composition
	return json.Unmarshal(residual, (*alias)(v))
}

// CompositionAttester is a generated nested backbone element.
type CompositionAttester struct {
	BackboneElement
	Mode        *CodeableConcept       `json:"mode,omitempty"`
	Time        *string                `json:"time,omitempty"`
	TimeElement *fhir.PrimitiveElement `json:"-"`
	Party       *Reference             `json:"party,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CompositionAttester) MarshalJSON() ([]byte, error) {
	type alias CompositionAttester
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCompositionAttesterSiblings(&v, encoded)
}

// marshalCompositionAttesterSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCompositionAttesterSiblings(v *CompositionAttester, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TimeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_time", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CompositionAttester) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_time"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TimeElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CompositionAttester
	return json.Unmarshal(residual, (*alias)(v))
}

// CompositionEvent is a generated nested backbone element.
type CompositionEvent struct {
	BackboneElement
	Period *Period             `json:"period,omitempty"`
	Detail []CodeableReference `json:"detail,omitempty"`
}

// CompositionSection is a generated nested backbone element.
type CompositionSection struct {
	BackboneElement
	Title        *string                `json:"title,omitempty"`
	TitleElement *fhir.PrimitiveElement `json:"-"`
	Code         *CodeableConcept       `json:"code,omitempty"`
	Author       []Reference            `json:"author,omitempty"`
	Focus        *Reference             `json:"focus,omitempty"`
	Text         *Narrative             `json:"text,omitempty"`
	OrderedBy    *CodeableConcept       `json:"orderedBy,omitempty"`
	Entry        []Reference            `json:"entry,omitempty"`
	EmptyReason  *CodeableConcept       `json:"emptyReason,omitempty"`
	Section      []CompositionSection   `json:"section,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v CompositionSection) MarshalJSON() ([]byte, error) {
	type alias CompositionSection
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalCompositionSectionSiblings(&v, encoded)
}

// marshalCompositionSectionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalCompositionSectionSiblings(v *CompositionSection, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_title", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *CompositionSection) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_title"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TitleElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias CompositionSection
	return json.Unmarshal(residual, (*alias)(v))
}
