// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// ContractResourceType is the FHIR resourceType discriminator for Contract.
const ContractResourceType = "Contract"

// Contract is the generated FHIR Contract resource.
type Contract struct {
	DomainResource
	Identifier             []Identifier               `json:"identifier,omitempty"`
	URL                    *string                    `json:"url,omitempty"`
	URLElement             *fhir.PrimitiveElement     `json:"-"`
	Version                *string                    `json:"version,omitempty"`
	VersionElement         *fhir.PrimitiveElement     `json:"-"`
	Status                 *string                    `json:"status,omitempty"`
	StatusElement          *fhir.PrimitiveElement     `json:"-"`
	LegalState             *CodeableConcept           `json:"legalState,omitempty"`
	InstantiatesCanonical  *Reference                 `json:"instantiatesCanonical,omitempty"`
	InstantiatesUri        *string                    `json:"instantiatesUri,omitempty"`
	InstantiatesUriElement *fhir.PrimitiveElement     `json:"-"`
	ContentDerivative      *CodeableConcept           `json:"contentDerivative,omitempty"`
	Issued                 *string                    `json:"issued,omitempty"`
	IssuedElement          *fhir.PrimitiveElement     `json:"-"`
	Applies                *Period                    `json:"applies,omitempty"`
	ExpirationType         *CodeableConcept           `json:"expirationType,omitempty"`
	Subject                []Reference                `json:"subject,omitempty"`
	Authority              []Reference                `json:"authority,omitempty"`
	Domain                 []Reference                `json:"domain,omitempty"`
	Site                   []Reference                `json:"site,omitempty"`
	Name                   *string                    `json:"name,omitempty"`
	NameElement            *fhir.PrimitiveElement     `json:"-"`
	Title                  *string                    `json:"title,omitempty"`
	TitleElement           *fhir.PrimitiveElement     `json:"-"`
	Subtitle               *string                    `json:"subtitle,omitempty"`
	SubtitleElement        *fhir.PrimitiveElement     `json:"-"`
	Alias                  []string                   `json:"alias,omitempty"`
	AliasElement           []*fhir.PrimitiveElement   `json:"-"`
	Author                 *Reference                 `json:"author,omitempty"`
	Scope                  *CodeableConcept           `json:"scope,omitempty"`
	Topic                  *CodeableConcept           `json:"topic,omitempty"`
	Type                   *CodeableConcept           `json:"type,omitempty"`
	SubType                []CodeableConcept          `json:"subType,omitempty"`
	ContentDefinition      *ContractContentDefinition `json:"contentDefinition,omitempty"`
	Term                   []ContractTerm             `json:"term,omitempty"`
	SupportingInfo         []Reference                `json:"supportingInfo,omitempty"`
	RelevantHistory        []Reference                `json:"relevantHistory,omitempty"`
	Signer                 []ContractSigner           `json:"signer,omitempty"`
	Friendly               []ContractFriendly         `json:"friendly,omitempty"`
	Legal                  []ContractFriendly         `json:"legal,omitempty"`
	Rule                   []ContractFriendly         `json:"rule,omitempty"`
	LegallyBinding         *Attachment                `json:"legallyBinding,omitempty"`
}

// ResourceType returns the FHIR discriminator "Contract".
func (r *Contract) ResourceType() string { return ContractResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a Contract never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *Contract) MarshalJSON() ([]byte, error) {
	type alias Contract
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: ContractResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalContractSiblings(r, encoded)
}

// marshalContractSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalContractSiblings(v *Contract, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.URLElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_url", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.InstantiatesUriElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_instantiatesUri", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.IssuedElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_issued", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_title", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.SubtitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_subtitle", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.Alias), v.AliasElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_alias", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *Contract) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_url"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URLElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_instantiatesUri"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.InstantiatesUriElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_issued"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.IssuedElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_title"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_subtitle"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.SubtitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_alias"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.AliasElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias Contract
	return json.Unmarshal(residual, (*alias)(v))
}

// ContractContentDefinition is a generated nested backbone element.
type ContractContentDefinition struct {
	BackboneElement
	Type                     *CodeableConcept       `json:"type,omitempty"`
	SubType                  *CodeableConcept       `json:"subType,omitempty"`
	Publisher                *Reference             `json:"publisher,omitempty"`
	PublicationDate          *string                `json:"publicationDate,omitempty"`
	PublicationDateElement   *fhir.PrimitiveElement `json:"-"`
	PublicationStatus        *string                `json:"publicationStatus,omitempty"`
	PublicationStatusElement *fhir.PrimitiveElement `json:"-"`
	Copyright                *string                `json:"copyright,omitempty"`
	CopyrightElement         *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ContractContentDefinition) MarshalJSON() ([]byte, error) {
	type alias ContractContentDefinition
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalContractContentDefinitionSiblings(&v, encoded)
}

// marshalContractContentDefinitionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalContractContentDefinitionSiblings(v *ContractContentDefinition, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublicationDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publicationDate", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublicationStatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publicationStatus", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyright", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ContractContentDefinition) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_publicationDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublicationDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_publicationStatus"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublicationStatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyright"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ContractContentDefinition
	return json.Unmarshal(residual, (*alias)(v))
}

// ContractFriendly is a generated nested backbone element.
type ContractFriendly struct {
	BackboneElement
	Content *Attachment `json:"content,omitempty"`
}

// ContractSigner is a generated nested backbone element.
type ContractSigner struct {
	BackboneElement
	Type      *Coding     `json:"type,omitempty"`
	Party     *Reference  `json:"party,omitempty"`
	Signature []Signature `json:"signature,omitempty"`
}

// ContractTerm is a generated nested backbone element.
type ContractTerm struct {
	BackboneElement
	Identifier    *Identifier                 `json:"identifier,omitempty"`
	Issued        *string                     `json:"issued,omitempty"`
	IssuedElement *fhir.PrimitiveElement      `json:"-"`
	Applies       *Period                     `json:"applies,omitempty"`
	Topic         *CodeableConcept            `json:"topic,omitempty"`
	Type          *CodeableConcept            `json:"type,omitempty"`
	SubType       *CodeableConcept            `json:"subType,omitempty"`
	Text          *string                     `json:"text,omitempty"`
	TextElement   *fhir.PrimitiveElement      `json:"-"`
	SecurityLabel []ContractTermSecurityLabel `json:"securityLabel,omitempty"`
	Offer         *ContractTermOffer          `json:"offer,omitempty"`
	Asset         []ContractTermAsset         `json:"asset,omitempty"`
	Action        []ContractTermAction        `json:"action,omitempty"`
	Group         []ContractTerm              `json:"group,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ContractTerm) MarshalJSON() ([]byte, error) {
	type alias ContractTerm
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalContractTermSiblings(&v, encoded)
}

// marshalContractTermSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalContractTermSiblings(v *ContractTerm, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.IssuedElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_issued", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TextElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_text", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ContractTerm) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_issued"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.IssuedElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_text"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TextElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ContractTerm
	return json.Unmarshal(residual, (*alias)(v))
}

// ContractTermAction is a generated nested backbone element.
type ContractTermAction struct {
	BackboneElement
	DoNotPerform               *bool                    `json:"doNotPerform,omitempty"`
	DoNotPerformElement        *fhir.PrimitiveElement   `json:"-"`
	Type                       *CodeableConcept         `json:"type,omitempty"`
	Subject                    []ContractTermOfferParty `json:"subject,omitempty"`
	Intent                     *CodeableConcept         `json:"intent,omitempty"`
	LinkId                     []string                 `json:"linkId,omitempty"`
	LinkIdElement              []*fhir.PrimitiveElement `json:"-"`
	Status                     *CodeableConcept         `json:"status,omitempty"`
	Context                    *Reference               `json:"context,omitempty"`
	ContextLinkId              []string                 `json:"contextLinkId,omitempty"`
	ContextLinkIdElement       []*fhir.PrimitiveElement `json:"-"`
	Occurrence                 *string                  `json:"occurrence,omitempty"`
	Requester                  []Reference              `json:"requester,omitempty"`
	RequesterLinkId            []string                 `json:"requesterLinkId,omitempty"`
	RequesterLinkIdElement     []*fhir.PrimitiveElement `json:"-"`
	PerformerType              []CodeableConcept        `json:"performerType,omitempty"`
	PerformerRole              *CodeableConcept         `json:"performerRole,omitempty"`
	Performer                  *Reference               `json:"performer,omitempty"`
	PerformerLinkId            []string                 `json:"performerLinkId,omitempty"`
	PerformerLinkIdElement     []*fhir.PrimitiveElement `json:"-"`
	Reason                     []CodeableReference      `json:"reason,omitempty"`
	ReasonLinkId               []string                 `json:"reasonLinkId,omitempty"`
	ReasonLinkIdElement        []*fhir.PrimitiveElement `json:"-"`
	Note                       []Annotation             `json:"note,omitempty"`
	SecurityLabelNumber        []int32                  `json:"securityLabelNumber,omitempty"`
	SecurityLabelNumberElement []*fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ContractTermAction) MarshalJSON() ([]byte, error) {
	type alias ContractTermAction
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalContractTermActionSiblings(&v, encoded)
}

// marshalContractTermActionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalContractTermActionSiblings(v *ContractTermAction, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.DoNotPerformElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_doNotPerform", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.LinkId), v.LinkIdElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_linkId", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.ContextLinkId), v.ContextLinkIdElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_contextLinkId", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.RequesterLinkId), v.RequesterLinkIdElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_requesterLinkId", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.PerformerLinkId), v.PerformerLinkIdElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_performerLinkId", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.ReasonLinkId), v.ReasonLinkIdElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_reasonLinkId", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.SecurityLabelNumber), v.SecurityLabelNumberElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_securityLabelNumber", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ContractTermAction) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_doNotPerform"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DoNotPerformElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_linkId"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.LinkIdElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_contextLinkId"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.ContextLinkIdElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_requesterLinkId"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.RequesterLinkIdElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_performerLinkId"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.PerformerLinkIdElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_reasonLinkId"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.ReasonLinkIdElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_securityLabelNumber"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.SecurityLabelNumberElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ContractTermAction
	return json.Unmarshal(residual, (*alias)(v))
}

// ContractTermAsset is a generated nested backbone element.
type ContractTermAsset struct {
	BackboneElement
	Scope                      *CodeableConcept              `json:"scope,omitempty"`
	Type                       []CodeableConcept             `json:"type,omitempty"`
	TypeReference              []Reference                   `json:"typeReference,omitempty"`
	Subtype                    []CodeableConcept             `json:"subtype,omitempty"`
	Relationship               *Coding                       `json:"relationship,omitempty"`
	Context                    []ContractTermAssetContext    `json:"context,omitempty"`
	Condition                  *string                       `json:"condition,omitempty"`
	ConditionElement           *fhir.PrimitiveElement        `json:"-"`
	PeriodType                 []CodeableConcept             `json:"periodType,omitempty"`
	Period                     []Period                      `json:"period,omitempty"`
	UsePeriod                  []Period                      `json:"usePeriod,omitempty"`
	Text                       *string                       `json:"text,omitempty"`
	TextElement                *fhir.PrimitiveElement        `json:"-"`
	LinkId                     []string                      `json:"linkId,omitempty"`
	LinkIdElement              []*fhir.PrimitiveElement      `json:"-"`
	Answer                     []ContractTermOfferAnswer     `json:"answer,omitempty"`
	SecurityLabelNumber        []int32                       `json:"securityLabelNumber,omitempty"`
	SecurityLabelNumberElement []*fhir.PrimitiveElement      `json:"-"`
	ValuedItem                 []ContractTermAssetValuedItem `json:"valuedItem,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ContractTermAsset) MarshalJSON() ([]byte, error) {
	type alias ContractTermAsset
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalContractTermAssetSiblings(&v, encoded)
}

// marshalContractTermAssetSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalContractTermAssetSiblings(v *ContractTermAsset, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.ConditionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_condition", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TextElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_text", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.LinkId), v.LinkIdElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_linkId", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.SecurityLabelNumber), v.SecurityLabelNumberElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_securityLabelNumber", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ContractTermAsset) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_condition"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ConditionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_text"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TextElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_linkId"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.LinkIdElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_securityLabelNumber"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.SecurityLabelNumberElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ContractTermAsset
	return json.Unmarshal(residual, (*alias)(v))
}

// ContractTermAssetContext is a generated nested backbone element.
type ContractTermAssetContext struct {
	BackboneElement
	Reference   *Reference             `json:"reference,omitempty"`
	Code        []CodeableConcept      `json:"code,omitempty"`
	Text        *string                `json:"text,omitempty"`
	TextElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ContractTermAssetContext) MarshalJSON() ([]byte, error) {
	type alias ContractTermAssetContext
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalContractTermAssetContextSiblings(&v, encoded)
}

// marshalContractTermAssetContextSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalContractTermAssetContextSiblings(v *ContractTermAssetContext, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TextElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_text", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ContractTermAssetContext) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_text"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TextElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ContractTermAssetContext
	return json.Unmarshal(residual, (*alias)(v))
}

// ContractTermAssetValuedItem is a generated nested backbone element.
type ContractTermAssetValuedItem struct {
	BackboneElement
	Entity                     *CodeableConcept         `json:"entity,omitempty"`
	Identifier                 *Identifier              `json:"identifier,omitempty"`
	EffectiveTime              *string                  `json:"effectiveTime,omitempty"`
	EffectiveTimeElement       *fhir.PrimitiveElement   `json:"-"`
	Quantity                   *Quantity                `json:"quantity,omitempty"`
	UnitPrice                  *Money                   `json:"unitPrice,omitempty"`
	Factor                     *fhir.Decimal            `json:"factor,omitempty"`
	FactorElement              *fhir.PrimitiveElement   `json:"-"`
	Points                     *fhir.Decimal            `json:"points,omitempty"`
	PointsElement              *fhir.PrimitiveElement   `json:"-"`
	Net                        *Money                   `json:"net,omitempty"`
	Payment                    *string                  `json:"payment,omitempty"`
	PaymentElement             *fhir.PrimitiveElement   `json:"-"`
	PaymentDate                *string                  `json:"paymentDate,omitempty"`
	PaymentDateElement         *fhir.PrimitiveElement   `json:"-"`
	Responsible                *Reference               `json:"responsible,omitempty"`
	Recipient                  *Reference               `json:"recipient,omitempty"`
	LinkId                     []string                 `json:"linkId,omitempty"`
	LinkIdElement              []*fhir.PrimitiveElement `json:"-"`
	SecurityLabelNumber        []int32                  `json:"securityLabelNumber,omitempty"`
	SecurityLabelNumberElement []*fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ContractTermAssetValuedItem) MarshalJSON() ([]byte, error) {
	type alias ContractTermAssetValuedItem
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalContractTermAssetValuedItemSiblings(&v, encoded)
}

// marshalContractTermAssetValuedItemSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalContractTermAssetValuedItemSiblings(v *ContractTermAssetValuedItem, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.EffectiveTimeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_effectiveTime", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.FactorElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_factor", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PointsElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_points", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PaymentElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_payment", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PaymentDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_paymentDate", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.LinkId), v.LinkIdElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_linkId", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.SecurityLabelNumber), v.SecurityLabelNumberElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_securityLabelNumber", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ContractTermAssetValuedItem) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_effectiveTime"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.EffectiveTimeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_factor"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.FactorElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_points"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PointsElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_payment"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PaymentElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_paymentDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PaymentDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_linkId"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.LinkIdElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_securityLabelNumber"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.SecurityLabelNumberElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ContractTermAssetValuedItem
	return json.Unmarshal(residual, (*alias)(v))
}

// ContractTermOffer is a generated nested backbone element.
type ContractTermOffer struct {
	BackboneElement
	Identifier                 []Identifier              `json:"identifier,omitempty"`
	Party                      []ContractTermOfferParty  `json:"party,omitempty"`
	Topic                      *Reference                `json:"topic,omitempty"`
	Type                       *CodeableConcept          `json:"type,omitempty"`
	Decision                   *CodeableConcept          `json:"decision,omitempty"`
	DecisionMode               []CodeableConcept         `json:"decisionMode,omitempty"`
	Answer                     []ContractTermOfferAnswer `json:"answer,omitempty"`
	Text                       *string                   `json:"text,omitempty"`
	TextElement                *fhir.PrimitiveElement    `json:"-"`
	LinkId                     []string                  `json:"linkId,omitempty"`
	LinkIdElement              []*fhir.PrimitiveElement  `json:"-"`
	SecurityLabelNumber        []int32                   `json:"securityLabelNumber,omitempty"`
	SecurityLabelNumberElement []*fhir.PrimitiveElement  `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ContractTermOffer) MarshalJSON() ([]byte, error) {
	type alias ContractTermOffer
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalContractTermOfferSiblings(&v, encoded)
}

// marshalContractTermOfferSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalContractTermOfferSiblings(v *ContractTermOffer, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TextElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_text", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.LinkId), v.LinkIdElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_linkId", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.SecurityLabelNumber), v.SecurityLabelNumberElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_securityLabelNumber", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ContractTermOffer) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_text"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TextElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_linkId"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.LinkIdElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_securityLabelNumber"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.SecurityLabelNumberElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ContractTermOffer
	return json.Unmarshal(residual, (*alias)(v))
}

// ContractTermOfferAnswer is a generated nested backbone element.
type ContractTermOfferAnswer struct {
	BackboneElement
	Value *bool `json:"value,omitempty"`
}

// ContractTermOfferParty is a generated nested backbone element.
type ContractTermOfferParty struct {
	BackboneElement
	Reference []Reference      `json:"reference,omitempty"`
	Role      *CodeableConcept `json:"role,omitempty"`
}

// ContractTermSecurityLabel is a generated nested backbone element.
type ContractTermSecurityLabel struct {
	BackboneElement
	Number         []int32                  `json:"number,omitempty"`
	NumberElement  []*fhir.PrimitiveElement `json:"-"`
	Classification *Coding                  `json:"classification,omitempty"`
	Category       []Coding                 `json:"category,omitempty"`
	Control        []Coding                 `json:"control,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v ContractTermSecurityLabel) MarshalJSON() ([]byte, error) {
	type alias ContractTermSecurityLabel
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalContractTermSecurityLabelSiblings(&v, encoded)
}

// marshalContractTermSecurityLabelSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalContractTermSecurityLabelSiblings(v *ContractTermSecurityLabel, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.Number), v.NumberElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_number", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ContractTermSecurityLabel) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_number"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.NumberElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ContractTermSecurityLabel
	return json.Unmarshal(residual, (*alias)(v))
}
