// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// HealthcareServiceResourceType is the FHIR resourceType discriminator for HealthcareService.
const HealthcareServiceResourceType = "HealthcareService"

// HealthcareService is the generated FHIR HealthcareService resource.
type HealthcareService struct {
	DomainResource
	Identifier                 []Identifier                   `json:"identifier,omitempty"`
	Active                     *bool                          `json:"active,omitempty"`
	ActiveElement              *fhir.PrimitiveElement         `json:"-"`
	ProvidedBy                 *Reference                     `json:"providedBy,omitempty"`
	OfferedIn                  []Reference                    `json:"offeredIn,omitempty"`
	Category                   []CodeableConcept              `json:"category,omitempty"`
	Type                       []CodeableConcept              `json:"type,omitempty"`
	Specialty                  []CodeableConcept              `json:"specialty,omitempty"`
	Location                   []Reference                    `json:"location,omitempty"`
	Name                       *string                        `json:"name,omitempty"`
	NameElement                *fhir.PrimitiveElement         `json:"-"`
	Comment                    *string                        `json:"comment,omitempty"`
	CommentElement             *fhir.PrimitiveElement         `json:"-"`
	ExtraDetails               *string                        `json:"extraDetails,omitempty"`
	ExtraDetailsElement        *fhir.PrimitiveElement         `json:"-"`
	Photo                      *Attachment                    `json:"photo,omitempty"`
	Contact                    []ExtendedContactDetail        `json:"contact,omitempty"`
	CoverageArea               []Reference                    `json:"coverageArea,omitempty"`
	ServiceProvisionCode       []CodeableConcept              `json:"serviceProvisionCode,omitempty"`
	Eligibility                []HealthcareServiceEligibility `json:"eligibility,omitempty"`
	Program                    []CodeableConcept              `json:"program,omitempty"`
	Characteristic             []CodeableConcept              `json:"characteristic,omitempty"`
	Communication              []CodeableConcept              `json:"communication,omitempty"`
	ReferralMethod             []CodeableConcept              `json:"referralMethod,omitempty"`
	AppointmentRequired        *bool                          `json:"appointmentRequired,omitempty"`
	AppointmentRequiredElement *fhir.PrimitiveElement         `json:"-"`
	Availability               []Availability                 `json:"availability,omitempty"`
	Endpoint                   []Reference                    `json:"endpoint,omitempty"`
}

// ResourceType returns the FHIR discriminator "HealthcareService".
func (r *HealthcareService) ResourceType() string { return HealthcareServiceResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a HealthcareService never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *HealthcareService) MarshalJSON() ([]byte, error) {
	type alias HealthcareService
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: HealthcareServiceResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalHealthcareServiceSiblings(r, encoded)
}

// marshalHealthcareServiceSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalHealthcareServiceSiblings(v *HealthcareService, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.ActiveElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_active", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CommentElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_comment", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ExtraDetailsElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_extraDetails", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.AppointmentRequiredElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_appointmentRequired", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through fhir.UnmarshalResource so the concrete type behind the interface is recovered;
// the standard codec cannot decode a resource object into an interface.
func (v *HealthcareService) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_active"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ActiveElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_comment"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CommentElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_extraDetails"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ExtraDetailsElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_appointmentRequired"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.AppointmentRequiredElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := fhir.UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias HealthcareService
	return json.Unmarshal(residual, (*alias)(v))
}

// HealthcareServiceEligibility is a generated nested backbone element.
type HealthcareServiceEligibility struct {
	BackboneElement
	Code           *CodeableConcept       `json:"code,omitempty"`
	Comment        *string                `json:"comment,omitempty"`
	CommentElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v HealthcareServiceEligibility) MarshalJSON() ([]byte, error) {
	type alias HealthcareServiceEligibility
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalHealthcareServiceEligibilitySiblings(&v, encoded)
}

// marshalHealthcareServiceEligibilitySiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalHealthcareServiceEligibilitySiblings(v *HealthcareServiceEligibility, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.CommentElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_comment", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *HealthcareServiceEligibility) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_comment"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CommentElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias HealthcareServiceEligibility
	return json.Unmarshal(residual, (*alias)(v))
}
