// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// ManufacturedItemDefinitionResourceType is the FHIR resourceType discriminator for ManufacturedItemDefinition.
const ManufacturedItemDefinitionResourceType = "ManufacturedItemDefinition"

// ManufacturedItemDefinition is the generated FHIR ManufacturedItemDefinition resource.
type ManufacturedItemDefinition struct {
	DomainResource
	Identifier           []Identifier                          `json:"identifier,omitempty"`
	Status               *string                               `json:"status,omitempty"`
	StatusElement        *fhir.PrimitiveElement                `json:"-"`
	Name                 *string                               `json:"name,omitempty"`
	NameElement          *fhir.PrimitiveElement                `json:"-"`
	ManufacturedDoseForm *CodeableConcept                      `json:"manufacturedDoseForm,omitempty"`
	UnitOfPresentation   *CodeableConcept                      `json:"unitOfPresentation,omitempty"`
	Manufacturer         []Reference                           `json:"manufacturer,omitempty"`
	MarketingStatus      []MarketingStatus                     `json:"marketingStatus,omitempty"`
	Ingredient           []CodeableConcept                     `json:"ingredient,omitempty"`
	Property             []ManufacturedItemDefinitionProperty  `json:"property,omitempty"`
	Component            []ManufacturedItemDefinitionComponent `json:"component,omitempty"`
}

// ResourceType returns the FHIR discriminator "ManufacturedItemDefinition".
func (r *ManufacturedItemDefinition) ResourceType() string {
	return ManufacturedItemDefinitionResourceType
}

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a ManufacturedItemDefinition never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *ManufacturedItemDefinition) MarshalJSON() ([]byte, error) {
	type alias ManufacturedItemDefinition
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: ManufacturedItemDefinitionResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalManufacturedItemDefinitionSiblings(r, encoded)
}

// marshalManufacturedItemDefinitionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalManufacturedItemDefinitionSiblings(v *ManufacturedItemDefinition, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *ManufacturedItemDefinition) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias ManufacturedItemDefinition
	return json.Unmarshal(residual, (*alias)(v))
}

// ManufacturedItemDefinitionComponent is a generated nested backbone element.
type ManufacturedItemDefinitionComponent struct {
	BackboneElement
	Type        *CodeableConcept                                 `json:"type,omitempty"`
	Function    []CodeableConcept                                `json:"function,omitempty"`
	Amount      []Quantity                                       `json:"amount,omitempty"`
	Constituent []ManufacturedItemDefinitionComponentConstituent `json:"constituent,omitempty"`
	Property    []ManufacturedItemDefinitionProperty             `json:"property,omitempty"`
	Component   []ManufacturedItemDefinitionComponent            `json:"component,omitempty"`
}

// ManufacturedItemDefinitionComponentConstituent is a generated nested backbone element.
type ManufacturedItemDefinitionComponentConstituent struct {
	BackboneElement
	Amount        []Quantity          `json:"amount,omitempty"`
	Location      []CodeableConcept   `json:"location,omitempty"`
	Function      []CodeableConcept   `json:"function,omitempty"`
	HasIngredient []CodeableReference `json:"hasIngredient,omitempty"`
}

// ManufacturedItemDefinitionProperty is a generated nested backbone element.
type ManufacturedItemDefinitionProperty struct {
	BackboneElement
	Type  *CodeableConcept `json:"type,omitempty"`
	Value *CodeableConcept `json:"value,omitempty"`
}
