// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// MolecularSequenceResourceType is the FHIR resourceType discriminator for MolecularSequence.
const MolecularSequenceResourceType = "MolecularSequence"

// MolecularSequence is the generated FHIR MolecularSequence resource.
type MolecularSequence struct {
	DomainResource
	Identifier     []Identifier                `json:"identifier,omitempty"`
	Type           *SequenceType               `json:"type,omitempty"`
	TypeElement    *fhir.PrimitiveElement      `json:"-"`
	Subject        *Reference                  `json:"subject,omitempty"`
	Focus          []Reference                 `json:"focus,omitempty"`
	Specimen       *Reference                  `json:"specimen,omitempty"`
	Device         *Reference                  `json:"device,omitempty"`
	Performer      *Reference                  `json:"performer,omitempty"`
	Literal        *string                     `json:"literal,omitempty"`
	LiteralElement *fhir.PrimitiveElement      `json:"-"`
	Formatted      []Attachment                `json:"formatted,omitempty"`
	Relative       []MolecularSequenceRelative `json:"relative,omitempty"`
}

// ResourceType returns the FHIR discriminator "MolecularSequence".
func (r *MolecularSequence) ResourceType() string { return MolecularSequenceResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a MolecularSequence never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *MolecularSequence) MarshalJSON() ([]byte, error) {
	type alias MolecularSequence
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: MolecularSequenceResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalMolecularSequenceSiblings(r, encoded)
}

// marshalMolecularSequenceSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalMolecularSequenceSiblings(v *MolecularSequence, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TypeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_type", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.LiteralElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_literal", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through the release-local UnmarshalResource so the concrete type behind the interface
// is recovered as a resource of this release; the standard codec cannot decode a resource
// object into an interface.
func (v *MolecularSequence) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_type"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TypeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_literal"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.LiteralElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias MolecularSequence
	return json.Unmarshal(residual, (*alias)(v))
}

// MolecularSequenceRelative is a generated nested backbone element.
type MolecularSequenceRelative struct {
	BackboneElement
	CoordinateSystem       *CodeableConcept                           `json:"coordinateSystem,omitempty"`
	OrdinalPosition        *int32                                     `json:"ordinalPosition,omitempty"`
	OrdinalPositionElement *fhir.PrimitiveElement                     `json:"-"`
	SequenceRange          *Range                                     `json:"sequenceRange,omitempty"`
	StartingSequence       *MolecularSequenceRelativeStartingSequence `json:"startingSequence,omitempty"`
	Edit                   []MolecularSequenceRelativeEdit            `json:"edit,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v MolecularSequenceRelative) MarshalJSON() ([]byte, error) {
	type alias MolecularSequenceRelative
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalMolecularSequenceRelativeSiblings(&v, encoded)
}

// marshalMolecularSequenceRelativeSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalMolecularSequenceRelativeSiblings(v *MolecularSequenceRelative, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.OrdinalPositionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_ordinalPosition", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *MolecularSequenceRelative) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_ordinalPosition"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.OrdinalPositionElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias MolecularSequenceRelative
	return json.Unmarshal(residual, (*alias)(v))
}

// MolecularSequenceRelativeEdit is a generated nested backbone element.
type MolecularSequenceRelativeEdit struct {
	BackboneElement
	Start                      *int32                 `json:"start,omitempty"`
	StartElement               *fhir.PrimitiveElement `json:"-"`
	End                        *int32                 `json:"end,omitempty"`
	EndElement                 *fhir.PrimitiveElement `json:"-"`
	ReplacementSequence        *string                `json:"replacementSequence,omitempty"`
	ReplacementSequenceElement *fhir.PrimitiveElement `json:"-"`
	ReplacedSequence           *string                `json:"replacedSequence,omitempty"`
	ReplacedSequenceElement    *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v MolecularSequenceRelativeEdit) MarshalJSON() ([]byte, error) {
	type alias MolecularSequenceRelativeEdit
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalMolecularSequenceRelativeEditSiblings(&v, encoded)
}

// marshalMolecularSequenceRelativeEditSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalMolecularSequenceRelativeEditSiblings(v *MolecularSequenceRelativeEdit, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.StartElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_start", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.EndElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_end", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ReplacementSequenceElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_replacementSequence", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ReplacedSequenceElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_replacedSequence", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *MolecularSequenceRelativeEdit) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_start"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StartElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_end"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.EndElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_replacementSequence"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ReplacementSequenceElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_replacedSequence"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ReplacedSequenceElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias MolecularSequenceRelativeEdit
	return json.Unmarshal(residual, (*alias)(v))
}

// MolecularSequenceRelativeStartingSequence is a generated nested backbone element.
type MolecularSequenceRelativeStartingSequence struct {
	BackboneElement
	GenomeAssembly          *CodeableConcept       `json:"genomeAssembly,omitempty"`
	Chromosome              *CodeableConcept       `json:"chromosome,omitempty"`
	SequenceCodeableConcept *CodeableConcept       `json:"sequenceCodeableConcept,omitempty"`
	SequenceString          *FHIRString            `json:"sequenceString,omitempty"`
	SequenceReference       *Reference             `json:"sequenceReference,omitempty"`
	WindowStart             *int32                 `json:"windowStart,omitempty"`
	WindowStartElement      *fhir.PrimitiveElement `json:"-"`
	WindowEnd               *int32                 `json:"windowEnd,omitempty"`
	WindowEndElement        *fhir.PrimitiveElement `json:"-"`
	Orientation             *OrientationType       `json:"orientation,omitempty"`
	OrientationElement      *fhir.PrimitiveElement `json:"-"`
	Strand                  *StrandType            `json:"strand,omitempty"`
	StrandElement           *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v MolecularSequenceRelativeStartingSequence) MarshalJSON() ([]byte, error) {
	type alias MolecularSequenceRelativeStartingSequence
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalMolecularSequenceRelativeStartingSequenceSiblings(&v, encoded)
}

// marshalMolecularSequenceRelativeStartingSequenceSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalMolecularSequenceRelativeStartingSequenceSiblings(v *MolecularSequenceRelativeStartingSequence, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.WindowStartElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_windowStart", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.WindowEndElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_windowEnd", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.OrientationElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_orientation", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StrandElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_strand", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *MolecularSequenceRelativeStartingSequence) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_windowStart"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.WindowStartElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_windowEnd"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.WindowEndElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_orientation"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.OrientationElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_strand"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StrandElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias MolecularSequenceRelativeStartingSequence
	return json.Unmarshal(residual, (*alias)(v))
}

// MolecularSequenceRelativeStartingSequenceSequence is the sealed value interface for the sequence[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isMolecularSequenceRelativeStartingSequenceSequence marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type MolecularSequenceRelativeStartingSequenceSequence interface{ isMolecularSequenceRelativeStartingSequenceSequence() }

func (CodeableConcept) isMolecularSequenceRelativeStartingSequenceSequence() {}
func (FHIRString) isMolecularSequenceRelativeStartingSequenceSequence()      {}
func (Reference) isMolecularSequenceRelativeStartingSequenceSequence()       {}

// Sequence returns the value set in the sequence[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *MolecularSequenceRelativeStartingSequence) Sequence() (MolecularSequenceRelativeStartingSequenceSequence, bool) {
	switch {
	case r.SequenceCodeableConcept != nil:
		return *r.SequenceCodeableConcept, true
	case r.SequenceString != nil:
		return *r.SequenceString, true
	case r.SequenceReference != nil:
		return *r.SequenceReference, true
	}
	return nil, false
}

// SetSequenceCodeableConcept sets sequence[x] to a CodeableConcept and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *MolecularSequenceRelativeStartingSequence) SetSequenceCodeableConcept(v CodeableConcept) {
	r.SequenceCodeableConcept = nil
	r.SequenceString = nil
	r.SequenceReference = nil
	r.SequenceCodeableConcept = &v
}

// SetSequenceString sets sequence[x] to a FHIRString (the
// release primitive wrapper that carries the isMolecularSequenceRelativeStartingSequenceSequence marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *MolecularSequenceRelativeStartingSequence) SetSequenceString(v FHIRString) {
	r.SequenceCodeableConcept = nil
	r.SequenceString = nil
	r.SequenceReference = nil
	r.SequenceString = &v
}

// SetSequenceReference sets sequence[x] to a Reference and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *MolecularSequenceRelativeStartingSequence) SetSequenceReference(v Reference) {
	r.SequenceCodeableConcept = nil
	r.SequenceString = nil
	r.SequenceReference = nil
	r.SequenceReference = &v
}
