// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// PaymentReconciliationResourceType is the FHIR resourceType discriminator for PaymentReconciliation.
const PaymentReconciliationResourceType = "PaymentReconciliation"

// PaymentReconciliation is the generated FHIR PaymentReconciliation resource.
type PaymentReconciliation struct {
	DomainResource
	Identifier             []Identifier                       `json:"identifier,omitempty"`
	Type                   *CodeableConcept                   `json:"type,omitempty"`
	Status                 *string                            `json:"status,omitempty"`
	StatusElement          *fhir.PrimitiveElement             `json:"-"`
	Kind                   *CodeableConcept                   `json:"kind,omitempty"`
	Period                 *Period                            `json:"period,omitempty"`
	Created                *string                            `json:"created,omitempty"`
	CreatedElement         *fhir.PrimitiveElement             `json:"-"`
	Enterer                *Reference                         `json:"enterer,omitempty"`
	IssuerType             *CodeableConcept                   `json:"issuerType,omitempty"`
	PaymentIssuer          *Reference                         `json:"paymentIssuer,omitempty"`
	Request                *Reference                         `json:"request,omitempty"`
	Requestor              *Reference                         `json:"requestor,omitempty"`
	Outcome                *string                            `json:"outcome,omitempty"`
	OutcomeElement         *fhir.PrimitiveElement             `json:"-"`
	Disposition            *string                            `json:"disposition,omitempty"`
	DispositionElement     *fhir.PrimitiveElement             `json:"-"`
	Date                   *string                            `json:"date,omitempty"`
	DateElement            *fhir.PrimitiveElement             `json:"-"`
	Location               *Reference                         `json:"location,omitempty"`
	Method                 *CodeableConcept                   `json:"method,omitempty"`
	CardBrand              *string                            `json:"cardBrand,omitempty"`
	CardBrandElement       *fhir.PrimitiveElement             `json:"-"`
	AccountNumber          *string                            `json:"accountNumber,omitempty"`
	AccountNumberElement   *fhir.PrimitiveElement             `json:"-"`
	ExpirationDate         *string                            `json:"expirationDate,omitempty"`
	ExpirationDateElement  *fhir.PrimitiveElement             `json:"-"`
	Processor              *string                            `json:"processor,omitempty"`
	ProcessorElement       *fhir.PrimitiveElement             `json:"-"`
	ReferenceNumber        *string                            `json:"referenceNumber,omitempty"`
	ReferenceNumberElement *fhir.PrimitiveElement             `json:"-"`
	Authorization          *string                            `json:"authorization,omitempty"`
	AuthorizationElement   *fhir.PrimitiveElement             `json:"-"`
	TenderedAmount         *Money                             `json:"tenderedAmount,omitempty"`
	ReturnedAmount         *Money                             `json:"returnedAmount,omitempty"`
	Amount                 *Money                             `json:"amount,omitempty"`
	PaymentIdentifier      *Identifier                        `json:"paymentIdentifier,omitempty"`
	Allocation             []PaymentReconciliationAllocation  `json:"allocation,omitempty"`
	FormCode               *CodeableConcept                   `json:"formCode,omitempty"`
	ProcessNote            []PaymentReconciliationProcessNote `json:"processNote,omitempty"`
}

// ResourceType returns the FHIR discriminator "PaymentReconciliation".
func (r *PaymentReconciliation) ResourceType() string { return PaymentReconciliationResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a PaymentReconciliation never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *PaymentReconciliation) MarshalJSON() ([]byte, error) {
	type alias PaymentReconciliation
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: PaymentReconciliationResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalPaymentReconciliationSiblings(r, encoded)
}

// marshalPaymentReconciliationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalPaymentReconciliationSiblings(v *PaymentReconciliation, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CreatedElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_created", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.OutcomeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_outcome", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DispositionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_disposition", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CardBrandElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_cardBrand", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.AccountNumberElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_accountNumber", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ExpirationDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_expirationDate", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ProcessorElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_processor", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ReferenceNumberElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_referenceNumber", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.AuthorizationElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_authorization", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *PaymentReconciliation) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_created"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CreatedElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_outcome"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.OutcomeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_disposition"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DispositionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_cardBrand"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CardBrandElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_accountNumber"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.AccountNumberElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_expirationDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ExpirationDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_processor"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ProcessorElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_referenceNumber"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ReferenceNumberElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_authorization"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.AuthorizationElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias PaymentReconciliation
	return json.Unmarshal(residual, (*alias)(v))
}

// PaymentReconciliationAllocation is a generated nested backbone element.
type PaymentReconciliationAllocation struct {
	BackboneElement
	Identifier            *Identifier            `json:"identifier,omitempty"`
	Predecessor           *Identifier            `json:"predecessor,omitempty"`
	Target                *Reference             `json:"target,omitempty"`
	TargetItemString      *FHIRString            `json:"targetItemString,omitempty"`
	TargetItemIdentifier  *Identifier            `json:"targetItemIdentifier,omitempty"`
	TargetItemPositiveInt *FHIRPositiveInt       `json:"targetItemPositiveInt,omitempty"`
	Encounter             *Reference             `json:"encounter,omitempty"`
	Account               *Reference             `json:"account,omitempty"`
	Type                  *CodeableConcept       `json:"type,omitempty"`
	Submitter             *Reference             `json:"submitter,omitempty"`
	Response              *Reference             `json:"response,omitempty"`
	Date                  *string                `json:"date,omitempty"`
	DateElement           *fhir.PrimitiveElement `json:"-"`
	Responsible           *Reference             `json:"responsible,omitempty"`
	Payee                 *Reference             `json:"payee,omitempty"`
	Amount                *Money                 `json:"amount,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v PaymentReconciliationAllocation) MarshalJSON() ([]byte, error) {
	type alias PaymentReconciliationAllocation
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalPaymentReconciliationAllocationSiblings(&v, encoded)
}

// marshalPaymentReconciliationAllocationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalPaymentReconciliationAllocationSiblings(v *PaymentReconciliationAllocation, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *PaymentReconciliationAllocation) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias PaymentReconciliationAllocation
	return json.Unmarshal(residual, (*alias)(v))
}

// PaymentReconciliationAllocationTargetItem is the sealed value interface for the targetItem[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isPaymentReconciliationAllocationTargetItem marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type PaymentReconciliationAllocationTargetItem interface{ isPaymentReconciliationAllocationTargetItem() }

func (FHIRString) isPaymentReconciliationAllocationTargetItem()      {}
func (Identifier) isPaymentReconciliationAllocationTargetItem()      {}
func (FHIRPositiveInt) isPaymentReconciliationAllocationTargetItem() {}

// TargetItem returns the value set in the targetItem[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *PaymentReconciliationAllocation) TargetItem() (PaymentReconciliationAllocationTargetItem, bool) {
	switch {
	case r.TargetItemString != nil:
		return *r.TargetItemString, true
	case r.TargetItemIdentifier != nil:
		return *r.TargetItemIdentifier, true
	case r.TargetItemPositiveInt != nil:
		return *r.TargetItemPositiveInt, true
	}
	return nil, false
}

// SetTargetItemString sets targetItem[x] to a FHIRString (the
// release primitive wrapper that carries the isPaymentReconciliationAllocationTargetItem marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *PaymentReconciliationAllocation) SetTargetItemString(v FHIRString) {
	r.TargetItemString = nil
	r.TargetItemIdentifier = nil
	r.TargetItemPositiveInt = nil
	r.TargetItemString = &v
}

// SetTargetItemIdentifier sets targetItem[x] to a Identifier and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *PaymentReconciliationAllocation) SetTargetItemIdentifier(v Identifier) {
	r.TargetItemString = nil
	r.TargetItemIdentifier = nil
	r.TargetItemPositiveInt = nil
	r.TargetItemIdentifier = &v
}

// SetTargetItemPositiveInt sets targetItem[x] to a FHIRPositiveInt (the
// release primitive wrapper that carries the isPaymentReconciliationAllocationTargetItem marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *PaymentReconciliationAllocation) SetTargetItemPositiveInt(v FHIRPositiveInt) {
	r.TargetItemString = nil
	r.TargetItemIdentifier = nil
	r.TargetItemPositiveInt = nil
	r.TargetItemPositiveInt = &v
}

// PaymentReconciliationProcessNote is a generated nested backbone element.
type PaymentReconciliationProcessNote struct {
	BackboneElement
	Type        *string                `json:"type,omitempty"`
	TypeElement *fhir.PrimitiveElement `json:"-"`
	Text        *string                `json:"text,omitempty"`
	TextElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v PaymentReconciliationProcessNote) MarshalJSON() ([]byte, error) {
	type alias PaymentReconciliationProcessNote
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalPaymentReconciliationProcessNoteSiblings(&v, encoded)
}

// marshalPaymentReconciliationProcessNoteSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalPaymentReconciliationProcessNoteSiblings(v *PaymentReconciliationProcessNote, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TypeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_type", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TextElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_text", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *PaymentReconciliationProcessNote) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_type"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TypeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_text"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TextElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias PaymentReconciliationProcessNote
	return json.Unmarshal(residual, (*alias)(v))
}
