// Code generated by fhir-gen; DO NOT EDIT.

package r5

// Period is the generated FHIR Period datatype.
type Period struct {
	Start *string `json:"start,omitempty"`
	End   *string `json:"end,omitempty"`
}
