// Code generated by fhir-gen; DO NOT EDIT.

package r5

// Ratio is the generated FHIR Ratio datatype.
type Ratio struct {
	Element
	Numerator   *Quantity `json:"numerator,omitempty"`
	Denominator *Quantity `json:"denominator,omitempty"`
}
