// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// SubstanceDefinitionResourceType is the FHIR resourceType discriminator for SubstanceDefinition.
const SubstanceDefinitionResourceType = "SubstanceDefinition"

// SubstanceDefinition is the generated FHIR SubstanceDefinition resource.
type SubstanceDefinition struct {
	DomainResource
	Identifier           []Identifier                          `json:"identifier,omitempty"`
	Version              *string                               `json:"version,omitempty"`
	VersionElement       *fhir.PrimitiveElement                `json:"-"`
	Status               *CodeableConcept                      `json:"status,omitempty"`
	Classification       []CodeableConcept                     `json:"classification,omitempty"`
	Domain               *CodeableConcept                      `json:"domain,omitempty"`
	Grade                []CodeableConcept                     `json:"grade,omitempty"`
	Description          *string                               `json:"description,omitempty"`
	DescriptionElement   *fhir.PrimitiveElement                `json:"-"`
	InformationSource    []Reference                           `json:"informationSource,omitempty"`
	Note                 []Annotation                          `json:"note,omitempty"`
	Manufacturer         []Reference                           `json:"manufacturer,omitempty"`
	Supplier             []Reference                           `json:"supplier,omitempty"`
	Moiety               []SubstanceDefinitionMoiety           `json:"moiety,omitempty"`
	Characterization     []SubstanceDefinitionCharacterization `json:"characterization,omitempty"`
	Property             []SubstanceDefinitionProperty         `json:"property,omitempty"`
	ReferenceInformation *Reference                            `json:"referenceInformation,omitempty"`
	MolecularWeight      []SubstanceDefinitionMolecularWeight  `json:"molecularWeight,omitempty"`
	Structure            *SubstanceDefinitionStructure         `json:"structure,omitempty"`
	Code                 []SubstanceDefinitionCode             `json:"code,omitempty"`
	Name                 []SubstanceDefinitionName             `json:"name,omitempty"`
	Relationship         []SubstanceDefinitionRelationship     `json:"relationship,omitempty"`
	NucleicAcid          *Reference                            `json:"nucleicAcid,omitempty"`
	Polymer              *Reference                            `json:"polymer,omitempty"`
	Protein              *Reference                            `json:"protein,omitempty"`
	SourceMaterial       *SubstanceDefinitionSourceMaterial    `json:"sourceMaterial,omitempty"`
}

// ResourceType returns the FHIR discriminator "SubstanceDefinition".
func (r *SubstanceDefinition) ResourceType() string { return SubstanceDefinitionResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a SubstanceDefinition never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *SubstanceDefinition) MarshalJSON() ([]byte, error) {
	type alias SubstanceDefinition
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: SubstanceDefinitionResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalSubstanceDefinitionSiblings(r, encoded)
}

// marshalSubstanceDefinitionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalSubstanceDefinitionSiblings(v *SubstanceDefinition, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through the release-local UnmarshalResource so the concrete type behind the interface
// is recovered as a resource of this release; the standard codec cannot decode a resource
// object into an interface.
func (v *SubstanceDefinition) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias SubstanceDefinition
	return json.Unmarshal(residual, (*alias)(v))
}

// SubstanceDefinitionCharacterization is a generated nested backbone element.
type SubstanceDefinitionCharacterization struct {
	BackboneElement
	Technique          *CodeableConcept       `json:"technique,omitempty"`
	Form               *CodeableConcept       `json:"form,omitempty"`
	Description        *string                `json:"description,omitempty"`
	DescriptionElement *fhir.PrimitiveElement `json:"-"`
	File               []Attachment           `json:"file,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v SubstanceDefinitionCharacterization) MarshalJSON() ([]byte, error) {
	type alias SubstanceDefinitionCharacterization
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalSubstanceDefinitionCharacterizationSiblings(&v, encoded)
}

// marshalSubstanceDefinitionCharacterizationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalSubstanceDefinitionCharacterizationSiblings(v *SubstanceDefinitionCharacterization, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *SubstanceDefinitionCharacterization) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias SubstanceDefinitionCharacterization
	return json.Unmarshal(residual, (*alias)(v))
}

// SubstanceDefinitionCode is a generated nested backbone element.
type SubstanceDefinitionCode struct {
	BackboneElement
	Code              *CodeableConcept       `json:"code,omitempty"`
	Status            *CodeableConcept       `json:"status,omitempty"`
	StatusDate        *string                `json:"statusDate,omitempty"`
	StatusDateElement *fhir.PrimitiveElement `json:"-"`
	Note              []Annotation           `json:"note,omitempty"`
	Source            []Reference            `json:"source,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v SubstanceDefinitionCode) MarshalJSON() ([]byte, error) {
	type alias SubstanceDefinitionCode
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalSubstanceDefinitionCodeSiblings(&v, encoded)
}

// marshalSubstanceDefinitionCodeSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalSubstanceDefinitionCodeSiblings(v *SubstanceDefinitionCode, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_statusDate", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *SubstanceDefinitionCode) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_statusDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusDateElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias SubstanceDefinitionCode
	return json.Unmarshal(residual, (*alias)(v))
}

// SubstanceDefinitionMoiety is a generated nested backbone element.
type SubstanceDefinitionMoiety struct {
	BackboneElement
	Role                    *CodeableConcept       `json:"role,omitempty"`
	Identifier              *Identifier            `json:"identifier,omitempty"`
	Name                    *string                `json:"name,omitempty"`
	NameElement             *fhir.PrimitiveElement `json:"-"`
	Stereochemistry         *CodeableConcept       `json:"stereochemistry,omitempty"`
	OpticalActivity         *CodeableConcept       `json:"opticalActivity,omitempty"`
	MolecularFormula        *string                `json:"molecularFormula,omitempty"`
	MolecularFormulaElement *fhir.PrimitiveElement `json:"-"`
	AmountQuantity          *Quantity              `json:"amountQuantity,omitempty"`
	AmountString            *FHIRString            `json:"amountString,omitempty"`
	MeasurementType         *CodeableConcept       `json:"measurementType,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v SubstanceDefinitionMoiety) MarshalJSON() ([]byte, error) {
	type alias SubstanceDefinitionMoiety
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalSubstanceDefinitionMoietySiblings(&v, encoded)
}

// marshalSubstanceDefinitionMoietySiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalSubstanceDefinitionMoietySiblings(v *SubstanceDefinitionMoiety, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.MolecularFormulaElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_molecularFormula", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *SubstanceDefinitionMoiety) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_molecularFormula"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.MolecularFormulaElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias SubstanceDefinitionMoiety
	return json.Unmarshal(residual, (*alias)(v))
}

// SubstanceDefinitionMoietyAmount is the sealed value interface for the amount[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isSubstanceDefinitionMoietyAmount marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type SubstanceDefinitionMoietyAmount interface{ isSubstanceDefinitionMoietyAmount() }

func (Quantity) isSubstanceDefinitionMoietyAmount()   {}
func (FHIRString) isSubstanceDefinitionMoietyAmount() {}

// Amount returns the value set in the amount[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *SubstanceDefinitionMoiety) Amount() (SubstanceDefinitionMoietyAmount, bool) {
	switch {
	case r.AmountQuantity != nil:
		return *r.AmountQuantity, true
	case r.AmountString != nil:
		return *r.AmountString, true
	}
	return nil, false
}

// SetAmountQuantity sets amount[x] to a Quantity and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionMoiety) SetAmountQuantity(v Quantity) {
	r.AmountQuantity = nil
	r.AmountString = nil
	r.AmountQuantity = &v
}

// SetAmountString sets amount[x] to a FHIRString (the
// release primitive wrapper that carries the isSubstanceDefinitionMoietyAmount marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionMoiety) SetAmountString(v FHIRString) {
	r.AmountQuantity = nil
	r.AmountString = nil
	r.AmountString = &v
}

// SubstanceDefinitionMolecularWeight is a generated nested backbone element.
type SubstanceDefinitionMolecularWeight struct {
	BackboneElement
	Method *CodeableConcept `json:"method,omitempty"`
	Type   *CodeableConcept `json:"type,omitempty"`
	Amount *Quantity        `json:"amount,omitempty"`
}

// SubstanceDefinitionName is a generated nested backbone element.
type SubstanceDefinitionName struct {
	BackboneElement
	Name             *string                           `json:"name,omitempty"`
	NameElement      *fhir.PrimitiveElement            `json:"-"`
	Type             *CodeableConcept                  `json:"type,omitempty"`
	Status           *CodeableConcept                  `json:"status,omitempty"`
	Preferred        *bool                             `json:"preferred,omitempty"`
	PreferredElement *fhir.PrimitiveElement            `json:"-"`
	Language         []CodeableConcept                 `json:"language,omitempty"`
	Domain           []CodeableConcept                 `json:"domain,omitempty"`
	Jurisdiction     []CodeableConcept                 `json:"jurisdiction,omitempty"`
	Synonym          []SubstanceDefinitionName         `json:"synonym,omitempty"`
	Translation      []SubstanceDefinitionName         `json:"translation,omitempty"`
	Official         []SubstanceDefinitionNameOfficial `json:"official,omitempty"`
	Source           []Reference                       `json:"source,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v SubstanceDefinitionName) MarshalJSON() ([]byte, error) {
	type alias SubstanceDefinitionName
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalSubstanceDefinitionNameSiblings(&v, encoded)
}

// marshalSubstanceDefinitionNameSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalSubstanceDefinitionNameSiblings(v *SubstanceDefinitionName, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PreferredElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_preferred", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *SubstanceDefinitionName) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_preferred"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PreferredElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias SubstanceDefinitionName
	return json.Unmarshal(residual, (*alias)(v))
}

// SubstanceDefinitionNameOfficial is a generated nested backbone element.
type SubstanceDefinitionNameOfficial struct {
	BackboneElement
	Authority   *CodeableConcept       `json:"authority,omitempty"`
	Status      *CodeableConcept       `json:"status,omitempty"`
	Date        *string                `json:"date,omitempty"`
	DateElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v SubstanceDefinitionNameOfficial) MarshalJSON() ([]byte, error) {
	type alias SubstanceDefinitionNameOfficial
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalSubstanceDefinitionNameOfficialSiblings(&v, encoded)
}

// marshalSubstanceDefinitionNameOfficialSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalSubstanceDefinitionNameOfficialSiblings(v *SubstanceDefinitionNameOfficial, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *SubstanceDefinitionNameOfficial) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias SubstanceDefinitionNameOfficial
	return json.Unmarshal(residual, (*alias)(v))
}

// SubstanceDefinitionProperty is a generated nested backbone element.
type SubstanceDefinitionProperty struct {
	BackboneElement
	Type                 *CodeableConcept `json:"type,omitempty"`
	ValueCodeableConcept *CodeableConcept `json:"valueCodeableConcept,omitempty"`
	ValueQuantity        *Quantity        `json:"valueQuantity,omitempty"`
	ValueDate            *FHIRDate        `json:"valueDate,omitempty"`
	ValueBoolean         *FHIRBoolean     `json:"valueBoolean,omitempty"`
	ValueAttachment      *Attachment      `json:"valueAttachment,omitempty"`
}

// SubstanceDefinitionPropertyValue is the sealed value interface for the value[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isSubstanceDefinitionPropertyValue marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type SubstanceDefinitionPropertyValue interface{ isSubstanceDefinitionPropertyValue() }

func (CodeableConcept) isSubstanceDefinitionPropertyValue() {}
func (Quantity) isSubstanceDefinitionPropertyValue()        {}
func (FHIRDate) isSubstanceDefinitionPropertyValue()        {}
func (FHIRBoolean) isSubstanceDefinitionPropertyValue()     {}
func (Attachment) isSubstanceDefinitionPropertyValue()      {}

// Value returns the value set in the value[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *SubstanceDefinitionProperty) Value() (SubstanceDefinitionPropertyValue, bool) {
	switch {
	case r.ValueCodeableConcept != nil:
		return *r.ValueCodeableConcept, true
	case r.ValueQuantity != nil:
		return *r.ValueQuantity, true
	case r.ValueDate != nil:
		return *r.ValueDate, true
	case r.ValueBoolean != nil:
		return *r.ValueBoolean, true
	case r.ValueAttachment != nil:
		return *r.ValueAttachment, true
	}
	return nil, false
}

// SetValueCodeableConcept sets value[x] to a CodeableConcept and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionProperty) SetValueCodeableConcept(v CodeableConcept) {
	r.ValueCodeableConcept = nil
	r.ValueQuantity = nil
	r.ValueDate = nil
	r.ValueBoolean = nil
	r.ValueAttachment = nil
	r.ValueCodeableConcept = &v
}

// SetValueQuantity sets value[x] to a Quantity and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionProperty) SetValueQuantity(v Quantity) {
	r.ValueCodeableConcept = nil
	r.ValueQuantity = nil
	r.ValueDate = nil
	r.ValueBoolean = nil
	r.ValueAttachment = nil
	r.ValueQuantity = &v
}

// SetValueDate sets value[x] to a FHIRDate (the
// release primitive wrapper that carries the isSubstanceDefinitionPropertyValue marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionProperty) SetValueDate(v FHIRDate) {
	r.ValueCodeableConcept = nil
	r.ValueQuantity = nil
	r.ValueDate = nil
	r.ValueBoolean = nil
	r.ValueAttachment = nil
	r.ValueDate = &v
}

// SetValueBoolean sets value[x] to a FHIRBoolean (the
// release primitive wrapper that carries the isSubstanceDefinitionPropertyValue marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionProperty) SetValueBoolean(v FHIRBoolean) {
	r.ValueCodeableConcept = nil
	r.ValueQuantity = nil
	r.ValueDate = nil
	r.ValueBoolean = nil
	r.ValueAttachment = nil
	r.ValueBoolean = &v
}

// SetValueAttachment sets value[x] to a Attachment and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionProperty) SetValueAttachment(v Attachment) {
	r.ValueCodeableConcept = nil
	r.ValueQuantity = nil
	r.ValueDate = nil
	r.ValueBoolean = nil
	r.ValueAttachment = nil
	r.ValueAttachment = &v
}

// SubstanceDefinitionRelationship is a generated nested backbone element.
type SubstanceDefinitionRelationship struct {
	BackboneElement
	SubstanceDefinitionReference       *Reference             `json:"substanceDefinitionReference,omitempty"`
	SubstanceDefinitionCodeableConcept *CodeableConcept       `json:"substanceDefinitionCodeableConcept,omitempty"`
	Type                               *CodeableConcept       `json:"type,omitempty"`
	IsDefining                         *bool                  `json:"isDefining,omitempty"`
	IsDefiningElement                  *fhir.PrimitiveElement `json:"-"`
	AmountQuantity                     *Quantity              `json:"amountQuantity,omitempty"`
	AmountRatio                        *Ratio                 `json:"amountRatio,omitempty"`
	AmountString                       *FHIRString            `json:"amountString,omitempty"`
	RatioHighLimitAmount               *Ratio                 `json:"ratioHighLimitAmount,omitempty"`
	Comparator                         *CodeableConcept       `json:"comparator,omitempty"`
	Source                             []Reference            `json:"source,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v SubstanceDefinitionRelationship) MarshalJSON() ([]byte, error) {
	type alias SubstanceDefinitionRelationship
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalSubstanceDefinitionRelationshipSiblings(&v, encoded)
}

// marshalSubstanceDefinitionRelationshipSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalSubstanceDefinitionRelationshipSiblings(v *SubstanceDefinitionRelationship, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.IsDefiningElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_isDefining", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *SubstanceDefinitionRelationship) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_isDefining"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.IsDefiningElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias SubstanceDefinitionRelationship
	return json.Unmarshal(residual, (*alias)(v))
}

// SubstanceDefinitionRelationshipSubstanceDefinition is the sealed value interface for the substanceDefinition[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isSubstanceDefinitionRelationshipSubstanceDefinition marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type SubstanceDefinitionRelationshipSubstanceDefinition interface{ isSubstanceDefinitionRelationshipSubstanceDefinition() }

func (Reference) isSubstanceDefinitionRelationshipSubstanceDefinition()       {}
func (CodeableConcept) isSubstanceDefinitionRelationshipSubstanceDefinition() {}

// SubstanceDefinition returns the value set in the substanceDefinition[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *SubstanceDefinitionRelationship) SubstanceDefinition() (SubstanceDefinitionRelationshipSubstanceDefinition, bool) {
	switch {
	case r.SubstanceDefinitionReference != nil:
		return *r.SubstanceDefinitionReference, true
	case r.SubstanceDefinitionCodeableConcept != nil:
		return *r.SubstanceDefinitionCodeableConcept, true
	}
	return nil, false
}

// SetSubstanceDefinitionReference sets substanceDefinition[x] to a Reference and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionRelationship) SetSubstanceDefinitionReference(v Reference) {
	r.SubstanceDefinitionReference = nil
	r.SubstanceDefinitionCodeableConcept = nil
	r.SubstanceDefinitionReference = &v
}

// SetSubstanceDefinitionCodeableConcept sets substanceDefinition[x] to a CodeableConcept and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionRelationship) SetSubstanceDefinitionCodeableConcept(v CodeableConcept) {
	r.SubstanceDefinitionReference = nil
	r.SubstanceDefinitionCodeableConcept = nil
	r.SubstanceDefinitionCodeableConcept = &v
}

// SubstanceDefinitionRelationshipAmount is the sealed value interface for the amount[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isSubstanceDefinitionRelationshipAmount marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type SubstanceDefinitionRelationshipAmount interface{ isSubstanceDefinitionRelationshipAmount() }

func (Quantity) isSubstanceDefinitionRelationshipAmount()   {}
func (Ratio) isSubstanceDefinitionRelationshipAmount()      {}
func (FHIRString) isSubstanceDefinitionRelationshipAmount() {}

// Amount returns the value set in the amount[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *SubstanceDefinitionRelationship) Amount() (SubstanceDefinitionRelationshipAmount, bool) {
	switch {
	case r.AmountQuantity != nil:
		return *r.AmountQuantity, true
	case r.AmountRatio != nil:
		return *r.AmountRatio, true
	case r.AmountString != nil:
		return *r.AmountString, true
	}
	return nil, false
}

// SetAmountQuantity sets amount[x] to a Quantity and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionRelationship) SetAmountQuantity(v Quantity) {
	r.AmountQuantity = nil
	r.AmountRatio = nil
	r.AmountString = nil
	r.AmountQuantity = &v
}

// SetAmountRatio sets amount[x] to a Ratio and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionRelationship) SetAmountRatio(v Ratio) {
	r.AmountQuantity = nil
	r.AmountRatio = nil
	r.AmountString = nil
	r.AmountRatio = &v
}

// SetAmountString sets amount[x] to a FHIRString (the
// release primitive wrapper that carries the isSubstanceDefinitionRelationshipAmount marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *SubstanceDefinitionRelationship) SetAmountString(v FHIRString) {
	r.AmountQuantity = nil
	r.AmountRatio = nil
	r.AmountString = nil
	r.AmountString = &v
}

// SubstanceDefinitionSourceMaterial is a generated nested backbone element.
type SubstanceDefinitionSourceMaterial struct {
	BackboneElement
	Type            *CodeableConcept  `json:"type,omitempty"`
	Genus           *CodeableConcept  `json:"genus,omitempty"`
	Species         *CodeableConcept  `json:"species,omitempty"`
	Part            *CodeableConcept  `json:"part,omitempty"`
	CountryOfOrigin []CodeableConcept `json:"countryOfOrigin,omitempty"`
}

// SubstanceDefinitionStructure is a generated nested backbone element.
type SubstanceDefinitionStructure struct {
	BackboneElement
	Stereochemistry                 *CodeableConcept                             `json:"stereochemistry,omitempty"`
	OpticalActivity                 *CodeableConcept                             `json:"opticalActivity,omitempty"`
	MolecularFormula                *string                                      `json:"molecularFormula,omitempty"`
	MolecularFormulaElement         *fhir.PrimitiveElement                       `json:"-"`
	MolecularFormulaByMoiety        *string                                      `json:"molecularFormulaByMoiety,omitempty"`
	MolecularFormulaByMoietyElement *fhir.PrimitiveElement                       `json:"-"`
	MolecularWeight                 *SubstanceDefinitionMolecularWeight          `json:"molecularWeight,omitempty"`
	Technique                       []CodeableConcept                            `json:"technique,omitempty"`
	SourceDocument                  []Reference                                  `json:"sourceDocument,omitempty"`
	Representation                  []SubstanceDefinitionStructureRepresentation `json:"representation,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v SubstanceDefinitionStructure) MarshalJSON() ([]byte, error) {
	type alias SubstanceDefinitionStructure
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalSubstanceDefinitionStructureSiblings(&v, encoded)
}

// marshalSubstanceDefinitionStructureSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalSubstanceDefinitionStructureSiblings(v *SubstanceDefinitionStructure, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.MolecularFormulaElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_molecularFormula", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.MolecularFormulaByMoietyElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_molecularFormulaByMoiety", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *SubstanceDefinitionStructure) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_molecularFormula"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.MolecularFormulaElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_molecularFormulaByMoiety"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.MolecularFormulaByMoietyElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias SubstanceDefinitionStructure
	return json.Unmarshal(residual, (*alias)(v))
}

// SubstanceDefinitionStructureRepresentation is a generated nested backbone element.
type SubstanceDefinitionStructureRepresentation struct {
	BackboneElement
	Type                  *CodeableConcept       `json:"type,omitempty"`
	Representation        *string                `json:"representation,omitempty"`
	RepresentationElement *fhir.PrimitiveElement `json:"-"`
	Format                *CodeableConcept       `json:"format,omitempty"`
	Document              *Reference             `json:"document,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v SubstanceDefinitionStructureRepresentation) MarshalJSON() ([]byte, error) {
	type alias SubstanceDefinitionStructureRepresentation
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalSubstanceDefinitionStructureRepresentationSiblings(&v, encoded)
}

// marshalSubstanceDefinitionStructureRepresentationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalSubstanceDefinitionStructureRepresentationSiblings(v *SubstanceDefinitionStructureRepresentation, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.RepresentationElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_representation", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *SubstanceDefinitionStructureRepresentation) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_representation"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.RepresentationElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias SubstanceDefinitionStructureRepresentation
	return json.Unmarshal(residual, (*alias)(v))
}
