// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// TerminologyCapabilitiesResourceType is the FHIR resourceType discriminator for TerminologyCapabilities.
const TerminologyCapabilitiesResourceType = "TerminologyCapabilities"

// TerminologyCapabilities is the generated FHIR TerminologyCapabilities resource.
type TerminologyCapabilities struct {
	DomainResource
	URL                   *string                                `json:"url,omitempty"`
	URLElement            *fhir.PrimitiveElement                 `json:"-"`
	Identifier            []Identifier                           `json:"identifier,omitempty"`
	Version               *string                                `json:"version,omitempty"`
	VersionElement        *fhir.PrimitiveElement                 `json:"-"`
	VersionAlgorithm      *string                                `json:"versionAlgorithm,omitempty"`
	Name                  *string                                `json:"name,omitempty"`
	NameElement           *fhir.PrimitiveElement                 `json:"-"`
	Title                 *string                                `json:"title,omitempty"`
	TitleElement          *fhir.PrimitiveElement                 `json:"-"`
	Status                *string                                `json:"status,omitempty"`
	StatusElement         *fhir.PrimitiveElement                 `json:"-"`
	Experimental          *bool                                  `json:"experimental,omitempty"`
	ExperimentalElement   *fhir.PrimitiveElement                 `json:"-"`
	Date                  *string                                `json:"date,omitempty"`
	DateElement           *fhir.PrimitiveElement                 `json:"-"`
	Publisher             *string                                `json:"publisher,omitempty"`
	PublisherElement      *fhir.PrimitiveElement                 `json:"-"`
	Contact               []ContactDetail                        `json:"contact,omitempty"`
	Description           *string                                `json:"description,omitempty"`
	DescriptionElement    *fhir.PrimitiveElement                 `json:"-"`
	UseContext            []UsageContext                         `json:"useContext,omitempty"`
	Jurisdiction          []CodeableConcept                      `json:"jurisdiction,omitempty"`
	Purpose               *string                                `json:"purpose,omitempty"`
	PurposeElement        *fhir.PrimitiveElement                 `json:"-"`
	Copyright             *string                                `json:"copyright,omitempty"`
	CopyrightElement      *fhir.PrimitiveElement                 `json:"-"`
	CopyrightLabel        *string                                `json:"copyrightLabel,omitempty"`
	CopyrightLabelElement *fhir.PrimitiveElement                 `json:"-"`
	Kind                  *string                                `json:"kind,omitempty"`
	KindElement           *fhir.PrimitiveElement                 `json:"-"`
	Software              *TerminologyCapabilitiesSoftware       `json:"software,omitempty"`
	Implementation        *TerminologyCapabilitiesImplementation `json:"implementation,omitempty"`
	LockedDate            *bool                                  `json:"lockedDate,omitempty"`
	LockedDateElement     *fhir.PrimitiveElement                 `json:"-"`
	CodeSystem            []TerminologyCapabilitiesCodeSystem    `json:"codeSystem,omitempty"`
	Expansion             *TerminologyCapabilitiesExpansion      `json:"expansion,omitempty"`
	CodeSearch            *string                                `json:"codeSearch,omitempty"`
	CodeSearchElement     *fhir.PrimitiveElement                 `json:"-"`
	ValidateCode          *TerminologyCapabilitiesValidateCode   `json:"validateCode,omitempty"`
	Translation           *TerminologyCapabilitiesTranslation    `json:"translation,omitempty"`
	Closure               *TerminologyCapabilitiesClosure        `json:"closure,omitempty"`
}

// ResourceType returns the FHIR discriminator "TerminologyCapabilities".
func (r *TerminologyCapabilities) ResourceType() string { return TerminologyCapabilitiesResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a TerminologyCapabilities never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *TerminologyCapabilities) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilities
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: TerminologyCapabilitiesResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesSiblings(r, encoded)
}

// marshalTerminologyCapabilitiesSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesSiblings(v *TerminologyCapabilities, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.URLElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_url", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_title", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ExperimentalElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_experimental", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublisherElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publisher", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PurposeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_purpose", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyright", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightLabelElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyrightLabel", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.KindElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_kind", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.LockedDateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_lockedDate", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CodeSearchElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_codeSearch", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilities) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_url"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URLElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_title"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_experimental"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ExperimentalElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_publisher"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublisherElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_purpose"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PurposeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyright"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyrightLabel"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightLabelElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_kind"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.KindElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_lockedDate"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.LockedDateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_codeSearch"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CodeSearchElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilities
	return json.Unmarshal(residual, (*alias)(v))
}

// TerminologyCapabilitiesClosure is a generated nested backbone element.
type TerminologyCapabilitiesClosure struct {
	BackboneElement
	Translation        *bool                  `json:"translation,omitempty"`
	TranslationElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TerminologyCapabilitiesClosure) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilitiesClosure
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesClosureSiblings(&v, encoded)
}

// marshalTerminologyCapabilitiesClosureSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesClosureSiblings(v *TerminologyCapabilitiesClosure, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TranslationElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_translation", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilitiesClosure) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_translation"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TranslationElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilitiesClosure
	return json.Unmarshal(residual, (*alias)(v))
}

// TerminologyCapabilitiesCodeSystem is a generated nested backbone element.
type TerminologyCapabilitiesCodeSystem struct {
	BackboneElement
	URI                *string                                    `json:"uri,omitempty"`
	URIElement         *fhir.PrimitiveElement                     `json:"-"`
	Version            []TerminologyCapabilitiesCodeSystemVersion `json:"version,omitempty"`
	Content            *string                                    `json:"content,omitempty"`
	ContentElement     *fhir.PrimitiveElement                     `json:"-"`
	Subsumption        *bool                                      `json:"subsumption,omitempty"`
	SubsumptionElement *fhir.PrimitiveElement                     `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TerminologyCapabilitiesCodeSystem) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilitiesCodeSystem
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesCodeSystemSiblings(&v, encoded)
}

// marshalTerminologyCapabilitiesCodeSystemSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesCodeSystemSiblings(v *TerminologyCapabilitiesCodeSystem, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.URIElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_uri", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ContentElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_content", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.SubsumptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_subsumption", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilitiesCodeSystem) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_uri"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URIElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_content"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ContentElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_subsumption"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.SubsumptionElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilitiesCodeSystem
	return json.Unmarshal(residual, (*alias)(v))
}

// TerminologyCapabilitiesCodeSystemVersion is a generated nested backbone element.
type TerminologyCapabilitiesCodeSystemVersion struct {
	BackboneElement
	Code                 *string                                          `json:"code,omitempty"`
	CodeElement          *fhir.PrimitiveElement                           `json:"-"`
	IsDefault            *bool                                            `json:"isDefault,omitempty"`
	IsDefaultElement     *fhir.PrimitiveElement                           `json:"-"`
	Compositional        *bool                                            `json:"compositional,omitempty"`
	CompositionalElement *fhir.PrimitiveElement                           `json:"-"`
	Language             []string                                         `json:"language,omitempty"`
	LanguageElement      []*fhir.PrimitiveElement                         `json:"-"`
	Filter               []TerminologyCapabilitiesCodeSystemVersionFilter `json:"filter,omitempty"`
	Property             []string                                         `json:"property,omitempty"`
	PropertyElement      []*fhir.PrimitiveElement                         `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TerminologyCapabilitiesCodeSystemVersion) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilitiesCodeSystemVersion
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesCodeSystemVersionSiblings(&v, encoded)
}

// marshalTerminologyCapabilitiesCodeSystemVersionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesCodeSystemVersionSiblings(v *TerminologyCapabilitiesCodeSystemVersion, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.CodeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_code", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.IsDefaultElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_isDefault", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CompositionalElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_compositional", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.Language), v.LanguageElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_language", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.Property), v.PropertyElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_property", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilitiesCodeSystemVersion) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_code"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CodeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_isDefault"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.IsDefaultElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_compositional"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CompositionalElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_language"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.LanguageElement = elements
	}
	if raw, ok := fhir.TakeRawField(obj, "_property"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.PropertyElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilitiesCodeSystemVersion
	return json.Unmarshal(residual, (*alias)(v))
}

// TerminologyCapabilitiesCodeSystemVersionFilter is a generated nested backbone element.
type TerminologyCapabilitiesCodeSystemVersionFilter struct {
	BackboneElement
	Code        *string                  `json:"code,omitempty"`
	CodeElement *fhir.PrimitiveElement   `json:"-"`
	Op          []string                 `json:"op,omitempty"`
	OpElement   []*fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TerminologyCapabilitiesCodeSystemVersionFilter) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilitiesCodeSystemVersionFilter
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesCodeSystemVersionFilterSiblings(&v, encoded)
}

// marshalTerminologyCapabilitiesCodeSystemVersionFilterSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesCodeSystemVersionFilterSiblings(v *TerminologyCapabilitiesCodeSystemVersionFilter, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.CodeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_code", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtensions(len(v.Op), v.OpElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_op", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilitiesCodeSystemVersionFilter) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_code"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CodeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_op"); ok {
		elements, err := fhir.UnmarshalPrimitiveExtensions(raw)
		if err != nil {
			return err
		}
		v.OpElement = elements
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilitiesCodeSystemVersionFilter
	return json.Unmarshal(residual, (*alias)(v))
}

// TerminologyCapabilitiesExpansion is a generated nested backbone element.
type TerminologyCapabilitiesExpansion struct {
	BackboneElement
	Hierarchical        *bool                                       `json:"hierarchical,omitempty"`
	HierarchicalElement *fhir.PrimitiveElement                      `json:"-"`
	Paging              *bool                                       `json:"paging,omitempty"`
	PagingElement       *fhir.PrimitiveElement                      `json:"-"`
	Incomplete          *bool                                       `json:"incomplete,omitempty"`
	IncompleteElement   *fhir.PrimitiveElement                      `json:"-"`
	Parameter           []TerminologyCapabilitiesExpansionParameter `json:"parameter,omitempty"`
	TextFilter          *string                                     `json:"textFilter,omitempty"`
	TextFilterElement   *fhir.PrimitiveElement                      `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TerminologyCapabilitiesExpansion) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilitiesExpansion
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesExpansionSiblings(&v, encoded)
}

// marshalTerminologyCapabilitiesExpansionSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesExpansionSiblings(v *TerminologyCapabilitiesExpansion, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.HierarchicalElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_hierarchical", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PagingElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_paging", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.IncompleteElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_incomplete", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TextFilterElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_textFilter", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilitiesExpansion) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_hierarchical"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.HierarchicalElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_paging"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PagingElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_incomplete"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.IncompleteElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_textFilter"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TextFilterElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilitiesExpansion
	return json.Unmarshal(residual, (*alias)(v))
}

// TerminologyCapabilitiesExpansionParameter is a generated nested backbone element.
type TerminologyCapabilitiesExpansionParameter struct {
	BackboneElement
	Name                 *string                `json:"name,omitempty"`
	NameElement          *fhir.PrimitiveElement `json:"-"`
	Documentation        *string                `json:"documentation,omitempty"`
	DocumentationElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TerminologyCapabilitiesExpansionParameter) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilitiesExpansionParameter
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesExpansionParameterSiblings(&v, encoded)
}

// marshalTerminologyCapabilitiesExpansionParameterSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesExpansionParameterSiblings(v *TerminologyCapabilitiesExpansionParameter, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DocumentationElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_documentation", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilitiesExpansionParameter) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_documentation"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DocumentationElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilitiesExpansionParameter
	return json.Unmarshal(residual, (*alias)(v))
}

// TerminologyCapabilitiesImplementation is a generated nested backbone element.
type TerminologyCapabilitiesImplementation struct {
	BackboneElement
	Description        *string                `json:"description,omitempty"`
	DescriptionElement *fhir.PrimitiveElement `json:"-"`
	URL                *string                `json:"url,omitempty"`
	URLElement         *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TerminologyCapabilitiesImplementation) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilitiesImplementation
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesImplementationSiblings(&v, encoded)
}

// marshalTerminologyCapabilitiesImplementationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesImplementationSiblings(v *TerminologyCapabilitiesImplementation, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.URLElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_url", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilitiesImplementation) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_url"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URLElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilitiesImplementation
	return json.Unmarshal(residual, (*alias)(v))
}

// TerminologyCapabilitiesSoftware is a generated nested backbone element.
type TerminologyCapabilitiesSoftware struct {
	BackboneElement
	Name           *string                `json:"name,omitempty"`
	NameElement    *fhir.PrimitiveElement `json:"-"`
	Version        *string                `json:"version,omitempty"`
	VersionElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TerminologyCapabilitiesSoftware) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilitiesSoftware
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesSoftwareSiblings(&v, encoded)
}

// marshalTerminologyCapabilitiesSoftwareSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesSoftwareSiblings(v *TerminologyCapabilitiesSoftware, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilitiesSoftware) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilitiesSoftware
	return json.Unmarshal(residual, (*alias)(v))
}

// TerminologyCapabilitiesTranslation is a generated nested backbone element.
type TerminologyCapabilitiesTranslation struct {
	BackboneElement
	NeedsMap        *bool                  `json:"needsMap,omitempty"`
	NeedsMapElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TerminologyCapabilitiesTranslation) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilitiesTranslation
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesTranslationSiblings(&v, encoded)
}

// marshalTerminologyCapabilitiesTranslationSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesTranslationSiblings(v *TerminologyCapabilitiesTranslation, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.NeedsMapElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_needsMap", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilitiesTranslation) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_needsMap"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NeedsMapElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilitiesTranslation
	return json.Unmarshal(residual, (*alias)(v))
}

// TerminologyCapabilitiesValidateCode is a generated nested backbone element.
type TerminologyCapabilitiesValidateCode struct {
	BackboneElement
	Translations        *bool                  `json:"translations,omitempty"`
	TranslationsElement *fhir.PrimitiveElement `json:"-"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TerminologyCapabilitiesValidateCode) MarshalJSON() ([]byte, error) {
	type alias TerminologyCapabilitiesValidateCode
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTerminologyCapabilitiesValidateCodeSiblings(&v, encoded)
}

// marshalTerminologyCapabilitiesValidateCodeSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTerminologyCapabilitiesValidateCodeSiblings(v *TerminologyCapabilitiesValidateCode, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.TranslationsElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_translations", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TerminologyCapabilitiesValidateCode) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_translations"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TranslationsElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TerminologyCapabilitiesValidateCode
	return json.Unmarshal(residual, (*alias)(v))
}
