// Code generated by fhir-gen; DO NOT EDIT.

package r5

import (
	"encoding/json"
	"github.com/codeninja55/go-radx/fhir"
)

// TestPlanResourceType is the FHIR resourceType discriminator for TestPlan.
const TestPlanResourceType = "TestPlan"

// TestPlan is the generated FHIR TestPlan resource.
type TestPlan struct {
	DomainResource
	URL                    *string                `json:"url,omitempty"`
	URLElement             *fhir.PrimitiveElement `json:"-"`
	Identifier             []Identifier           `json:"identifier,omitempty"`
	Version                *string                `json:"version,omitempty"`
	VersionElement         *fhir.PrimitiveElement `json:"-"`
	VersionAlgorithmString *FHIRString            `json:"versionAlgorithmString,omitempty"`
	VersionAlgorithmCoding *Coding                `json:"versionAlgorithmCoding,omitempty"`
	Name                   *string                `json:"name,omitempty"`
	NameElement            *fhir.PrimitiveElement `json:"-"`
	Title                  *string                `json:"title,omitempty"`
	TitleElement           *fhir.PrimitiveElement `json:"-"`
	Status                 *PublicationStatus     `json:"status,omitempty"`
	StatusElement          *fhir.PrimitiveElement `json:"-"`
	Experimental           *bool                  `json:"experimental,omitempty"`
	ExperimentalElement    *fhir.PrimitiveElement `json:"-"`
	Date                   *string                `json:"date,omitempty"`
	DateElement            *fhir.PrimitiveElement `json:"-"`
	Publisher              *string                `json:"publisher,omitempty"`
	PublisherElement       *fhir.PrimitiveElement `json:"-"`
	Contact                []ContactDetail        `json:"contact,omitempty"`
	Description            *string                `json:"description,omitempty"`
	DescriptionElement     *fhir.PrimitiveElement `json:"-"`
	UseContext             []UsageContext         `json:"useContext,omitempty"`
	Jurisdiction           []CodeableConcept      `json:"jurisdiction,omitempty"`
	Purpose                *string                `json:"purpose,omitempty"`
	PurposeElement         *fhir.PrimitiveElement `json:"-"`
	Copyright              *string                `json:"copyright,omitempty"`
	CopyrightElement       *fhir.PrimitiveElement `json:"-"`
	CopyrightLabel         *string                `json:"copyrightLabel,omitempty"`
	CopyrightLabelElement  *fhir.PrimitiveElement `json:"-"`
	Category               []CodeableConcept      `json:"category,omitempty"`
	Scope                  []Reference            `json:"scope,omitempty"`
	TestTools              *string                `json:"testTools,omitempty"`
	TestToolsElement       *fhir.PrimitiveElement `json:"-"`
	Dependency             []TestPlanDependency   `json:"dependency,omitempty"`
	ExitCriteria           *string                `json:"exitCriteria,omitempty"`
	ExitCriteriaElement    *fhir.PrimitiveElement `json:"-"`
	TestCase               []TestPlanTestCase     `json:"testCase,omitempty"`
}

// ResourceType returns the FHIR discriminator "TestPlan".
func (r *TestPlan) ResourceType() string { return TestPlanResourceType }

// MarshalJSON emits the resource with "resourceType" as the first JSON key, always
// carrying the type constant — even for a zero value, so a TestPlan never
// serialises an empty "resourceType". The primitive "_field" siblings are folded in
// afterwards: a scalar sibling is dropped when it carries no id or extension, and a
// repeating sibling's array is null-aligned with its value array so positions line
// up on the wire.
func (r *TestPlan) MarshalJSON() ([]byte, error) {
	type alias TestPlan
	encoded, err := json.Marshal(struct {
		ResourceType string `json:"resourceType"`
		*alias
	}{
		ResourceType: TestPlanResourceType,
		alias:        (*alias)(r),
	})
	if err != nil {
		return nil, err
	}
	return marshalTestPlanSiblings(r, encoded)
}

// marshalTestPlanSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTestPlanSiblings(v *TestPlan, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.URLElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_url", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.VersionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_version", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.NameElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_name", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TitleElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_title", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.StatusElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_status", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ExperimentalElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_experimental", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DateElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_date", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PublisherElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_publisher", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.PurposeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_purpose", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyright", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.CopyrightLabelElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_copyrightLabel", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.TestToolsElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_testTools", Value: raw})
	}
	if raw, err := fhir.MarshalPrimitiveExtension(v.ExitCriteriaElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_exitCriteria", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling and resource-typed field out of
// the object, decodes each into its companion field, then decodes the remaining keys
// into the value struct. A resource-typed field (the fhir.Resource interface) is decoded
// through the release-local UnmarshalResource so the concrete type behind the interface
// is recovered as a resource of this release; the standard codec cannot decode a resource
// object into an interface.
func (v *TestPlan) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_url"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.URLElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_version"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.VersionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_name"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NameElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_title"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TitleElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_status"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.StatusElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_experimental"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ExperimentalElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_date"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DateElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_publisher"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PublisherElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_purpose"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.PurposeElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyright"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_copyrightLabel"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.CopyrightLabelElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_testTools"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.TestToolsElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "_exitCriteria"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.ExitCriteriaElement = &element
	}
	if raw, ok := fhir.TakeRawField(obj, "contained"); ok {
		resources, err := UnmarshalResourceSlice(raw)
		if err != nil {
			return err
		}
		v.Contained = resources
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TestPlan
	return json.Unmarshal(residual, (*alias)(v))
}

// TestPlanVersionAlgorithm is the sealed value interface for the versionAlgorithm[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isTestPlanVersionAlgorithm marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type TestPlanVersionAlgorithm interface{ isTestPlanVersionAlgorithm() }

func (FHIRString) isTestPlanVersionAlgorithm() {}
func (Coding) isTestPlanVersionAlgorithm()     {}

// VersionAlgorithm returns the value set in the versionAlgorithm[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *TestPlan) VersionAlgorithm() (TestPlanVersionAlgorithm, bool) {
	switch {
	case r.VersionAlgorithmString != nil:
		return *r.VersionAlgorithmString, true
	case r.VersionAlgorithmCoding != nil:
		return *r.VersionAlgorithmCoding, true
	}
	return nil, false
}

// SetVersionAlgorithmString sets versionAlgorithm[x] to a FHIRString (the
// release primitive wrapper that carries the isTestPlanVersionAlgorithm marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *TestPlan) SetVersionAlgorithmString(v FHIRString) {
	r.VersionAlgorithmString = nil
	r.VersionAlgorithmCoding = nil
	r.VersionAlgorithmString = &v
}

// SetVersionAlgorithmCoding sets versionAlgorithm[x] to a Coding and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *TestPlan) SetVersionAlgorithmCoding(v Coding) {
	r.VersionAlgorithmString = nil
	r.VersionAlgorithmCoding = nil
	r.VersionAlgorithmCoding = &v
}

// TestPlanDependency is a generated nested backbone element.
type TestPlanDependency struct {
	BackboneElement
	Description        *string                `json:"description,omitempty"`
	DescriptionElement *fhir.PrimitiveElement `json:"-"`
	Predecessor        *Reference             `json:"predecessor,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TestPlanDependency) MarshalJSON() ([]byte, error) {
	type alias TestPlanDependency
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTestPlanDependencySiblings(&v, encoded)
}

// marshalTestPlanDependencySiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTestPlanDependencySiblings(v *TestPlanDependency, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.DescriptionElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_description", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TestPlanDependency) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_description"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.DescriptionElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TestPlanDependency
	return json.Unmarshal(residual, (*alias)(v))
}

// TestPlanTestCase is a generated nested backbone element.
type TestPlanTestCase struct {
	BackboneElement
	Sequence        *int32                      `json:"sequence,omitempty"`
	SequenceElement *fhir.PrimitiveElement      `json:"-"`
	Scope           []Reference                 `json:"scope,omitempty"`
	Dependency      []TestPlanDependency        `json:"dependency,omitempty"`
	TestRun         []TestPlanTestCaseTestRun   `json:"testRun,omitempty"`
	TestData        []TestPlanTestCaseTestData  `json:"testData,omitempty"`
	Assertion       []TestPlanTestCaseAssertion `json:"assertion,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TestPlanTestCase) MarshalJSON() ([]byte, error) {
	type alias TestPlanTestCase
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTestPlanTestCaseSiblings(&v, encoded)
}

// marshalTestPlanTestCaseSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTestPlanTestCaseSiblings(v *TestPlanTestCase, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.SequenceElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_sequence", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TestPlanTestCase) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_sequence"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.SequenceElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TestPlanTestCase
	return json.Unmarshal(residual, (*alias)(v))
}

// TestPlanTestCaseAssertion is a generated nested backbone element.
type TestPlanTestCaseAssertion struct {
	BackboneElement
	Type   []CodeableConcept   `json:"type,omitempty"`
	Object []CodeableReference `json:"object,omitempty"`
	Result []CodeableReference `json:"result,omitempty"`
}

// TestPlanTestCaseTestData is a generated nested backbone element.
type TestPlanTestCaseTestData struct {
	BackboneElement
	Type            *Coding     `json:"type,omitempty"`
	Content         *Reference  `json:"content,omitempty"`
	SourceString    *FHIRString `json:"sourceString,omitempty"`
	SourceReference *Reference  `json:"sourceReference,omitempty"`
}

// TestPlanTestCaseTestDataSource is the sealed value interface for the source[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isTestPlanTestCaseTestDataSource marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type TestPlanTestCaseTestDataSource interface{ isTestPlanTestCaseTestDataSource() }

func (FHIRString) isTestPlanTestCaseTestDataSource() {}
func (Reference) isTestPlanTestCaseTestDataSource()  {}

// Source returns the value set in the source[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *TestPlanTestCaseTestData) Source() (TestPlanTestCaseTestDataSource, bool) {
	switch {
	case r.SourceString != nil:
		return *r.SourceString, true
	case r.SourceReference != nil:
		return *r.SourceReference, true
	}
	return nil, false
}

// SetSourceString sets source[x] to a FHIRString (the
// release primitive wrapper that carries the isTestPlanTestCaseTestDataSource marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *TestPlanTestCaseTestData) SetSourceString(v FHIRString) {
	r.SourceString = nil
	r.SourceReference = nil
	r.SourceString = &v
}

// SetSourceReference sets source[x] to a Reference and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *TestPlanTestCaseTestData) SetSourceReference(v Reference) {
	r.SourceString = nil
	r.SourceReference = nil
	r.SourceReference = &v
}

// TestPlanTestCaseTestRun is a generated nested backbone element.
type TestPlanTestCaseTestRun struct {
	BackboneElement
	Narrative        *string                        `json:"narrative,omitempty"`
	NarrativeElement *fhir.PrimitiveElement         `json:"-"`
	Script           *TestPlanTestCaseTestRunScript `json:"script,omitempty"`
}

// MarshalJSON folds the backbone's primitive "_field" siblings into the encoded
// value: scalar siblings dropped when empty, repeating siblings null-aligned with
// their value arrays.
func (v TestPlanTestCaseTestRun) MarshalJSON() ([]byte, error) {
	type alias TestPlanTestCaseTestRun
	encoded, err := json.Marshal(alias(v))
	if err != nil {
		return nil, err
	}
	return marshalTestPlanTestCaseTestRunSiblings(&v, encoded)
}

// marshalTestPlanTestCaseTestRunSiblings appends the primitive "_field" siblings to the
// already-encoded object, preserving the value fields' canonical order: an empty
// scalar sibling and an un-extended repeating sibling are skipped, and a repeating
// sibling's array is null-aligned with its value array.
func marshalTestPlanTestCaseTestRunSiblings(v *TestPlanTestCaseTestRun, encoded []byte) ([]byte, error) {
	var siblings []fhir.RawSibling
	if raw, err := fhir.MarshalPrimitiveExtension(v.NarrativeElement); err != nil {
		return nil, err
	} else {
		siblings = append(siblings, fhir.RawSibling{Key: "_narrative", Value: raw})
	}
	return fhir.AppendSiblings(encoded, siblings)
}

// UnmarshalJSON lifts each primitive "_field" sibling out of the object, decodes it
// into its companion field, then decodes the remaining keys into the value struct.
func (v *TestPlanTestCaseTestRun) UnmarshalJSON(data []byte) error {
	obj, err := fhir.SplitRawObject(data)
	if err != nil {
		return err
	}
	if raw, ok := fhir.TakeRawField(obj, "_narrative"); ok {
		var element fhir.PrimitiveElement
		if err := json.Unmarshal(raw, &element); err != nil {
			return err
		}
		v.NarrativeElement = &element
	}
	residual, err := fhir.RemarshalObject(obj)
	if err != nil {
		return err
	}
	type alias TestPlanTestCaseTestRun
	return json.Unmarshal(residual, (*alias)(v))
}

// TestPlanTestCaseTestRunScript is a generated nested backbone element.
type TestPlanTestCaseTestRunScript struct {
	BackboneElement
	Language        *CodeableConcept `json:"language,omitempty"`
	SourceString    *FHIRString      `json:"sourceString,omitempty"`
	SourceReference *Reference       `json:"sourceReference,omitempty"`
}

// TestPlanTestCaseTestRunScriptSource is the sealed value interface for the source[x]
// choice group. It is implemented only by this package's branch types — the named
// datatype structs and the release primitive wrappers — through the unexported
// isTestPlanTestCaseTestRunScriptSource marker, so a built-in scalar can never satisfy it and the
// branch set stays closed.
type TestPlanTestCaseTestRunScriptSource interface{ isTestPlanTestCaseTestRunScriptSource() }

func (FHIRString) isTestPlanTestCaseTestRunScriptSource() {}
func (Reference) isTestPlanTestCaseTestRunScriptSource()  {}

// Source returns the value set in the source[x] choice
// group, or (nil, false) when no branch is set. The returned value is one of the
// branch types; a type switch recovers which branch was chosen.
func (r *TestPlanTestCaseTestRunScript) Source() (TestPlanTestCaseTestRunScriptSource, bool) {
	switch {
	case r.SourceString != nil:
		return *r.SourceString, true
	case r.SourceReference != nil:
		return *r.SourceReference, true
	}
	return nil, false
}

// SetSourceString sets source[x] to a FHIRString (the
// release primitive wrapper that carries the isTestPlanTestCaseTestRunScriptSource marker; the built-in
// scalar cannot) and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *TestPlanTestCaseTestRunScript) SetSourceString(v FHIRString) {
	r.SourceString = nil
	r.SourceReference = nil
	r.SourceString = &v
}

// SetSourceReference sets source[x] to a Reference and clears every other branch, so the group holds at most one
// value and marshals exactly one suffixed key.
func (r *TestPlanTestCaseTestRunScript) SetSourceReference(v Reference) {
	r.SourceString = nil
	r.SourceReference = nil
	r.SourceReference = &v
}
